### ISSUE TITLE
Add fmt library version number in changelog

### ISSUE THREAD

**Issue by azuresigma** [odygrd/quill#10]
Our application also uses fmt library, which is a great library. Quill has its copy of fmt in include/bundled/ directory. Right now our fmt library(6.1.2) seems to co-exist well with bundled/fmt. But in the future, quill can upgrade to a different fmt version. Users would like to know what version of fmt is supported/tested with a new quill release. It will be convenient to  just read changelog.md for this information.

**Comment by odygrd** [comment]
Yes sure I will do, I am planning to upgrade to `6.2.0` tonight and will add it to the changelog as well

**Comment by odygrd** [comment]
Fixed in bf820e5b83ad7cd7813b640e0f07ac2e6b949887
