### ISSUE TITLE
Performance sections improvement

### ISSUE THREAD

**Issue by Xottab-DUTY** [odygrd/quill#102]
From the first impression, performance section in the readme, has the tables with numbers... Unknown numbers.
The measure units are unclear and require looking at the benchmark code. I'm still unsure if it's nanoseconds.
Should be stated explicitly somewhere.

Also, it will be nice to also add processor info in addition to the info on which system benchmarks are done.

**Comment by odygrd** [comment]
Hello, the benchmark results are in nanoseconds, I have updated the Readme file. 
Latest benchmarks were done on `Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz`

**Comment by Xottab-DUTY** [comment]
Thank you!

> Latest benchmarks were done on Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz

Maybe, also add it to the readme?

**Comment by bl-ue** [comment]
👍🏻 6cd23621307937d266034f51207b477b93f93001

**Comment by Xottab-DUTY** [comment]
Thank you!
