### ISSUE TITLE
Test Issue: FileUtilities append_date_to_filename test expects local timezone to be GMT0

### ISSUE THREAD

**Issue by blakewoolbright** [odygrd/quill#104]
Looks like the FileUtilities test has a time zone issue that causes a false failure in some geo locations.  The append_date_to_filename test constructs a system_clock::time_point from epoch seconds(1583376945), and then serializes it to a suffix string for a log file and compares it to an expected result (2020-03-05).  The problem is that the input epoch timestamp translates to the date 2020-03-04 in some time zones and 2020-03-05 in others.  The test should probably manually override the current timezone setting internally before running the convert and append function.

Nice library folks.  I just started looking at it, but it's quite fancy.

**Comment by odygrd** [comment]
I think this should now happen anymore because `append_date_time_to_filename` takes a timezone in the latest versions. Feel free to reopen if it is still an issue ..
