### ISSUE TITLE
cannot create new formatter

### ISSUE THREAD

**Issue by fayce66** [odygrd/quill#111]
I am trying to create a new formatter as described in the documentation. The program compiles without problem but each time I run the application I have the following error:

undefined symbol: _ZN5quill6detail18TimestampFormatterC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8TimezoneE

My code is as below:
```

void DefaultLogger::init(const std::string &instance_name, const std::string &filename) {
    // enable console colours on the handler to stdout
    quill::enable_console_colours();
    // we will log to a file and to the console so we need to create 2 handlers
    auto *stdout_handler = quill::stdout_handler();
    // set a custom formatter for our handlers (no need for thread id)
    auto pat = QUILL_STRING("%(ascii_time) %(logger_name) %(filename):%(lineno) LOG_%(level_name) - %(message)");
    stdout_handler->set_pattern(pat, "%D %H:%M:%S.%Qns %z", quill::Timezone::GmtTime);
    // sets the default logger's handler to be the new handler with the custom format string
    quill::set_default_logger_handler(stdout_handler);
    // we don't want all log messages to be sent to the console
    // so we create a special log filter for the console handler
    stdout_handler->add_filter(std::make_unique<StdoutFilter>());
    // create file handler (will inherit default handler's format)
    auto *file_handler = quill::file_handler(filename, "w");
    // create our logger using both handlers - nb: the logs
    // going to the console will also print colour codes)
    logger_ = quill::create_logger(instance_name.c_str(), {file_handler, stdout_handler});
    // set default log level (log everything)
    set_log_level(quill::LogLevel::TraceL3);
    // enable a backtrace that will get flushed when we log CRITICAL
    //logger_->init_backtrace(3, quill::LogLevel::Critical);
    // start the logging backend thread
    quill::start();
}
```

I also tried without the time format and timezone:
  stdout_handler->set_pattern(pat);

and I have the same error. Am I doing something wrong?

BTW, great library! simple and efficient!

**Comment by odygrd** [comment]
Hello and thanks! 
It is hard to tell just from this error. 

It looks like you have 
a) included the header files, but have not compiled quill as a library or you have not linked against it
b) compiled quill with C++11 `std::string` ABI but your application is trying to building without the new string ABI

Quill is **not** a header only library, you need to compile it as a library (static or shared) and then link against it. It looks like you are just including the header files above but not linking against it.

Please can you provide more information in order to help

What Os/compiler are you using ?
How are you using quill, is it via cmake or something else ?

**Comment by fayce66** [comment]
Hello, first of all thanks for the feedback and this great library.

I compiled quill on my Ubuntu 20.04 desktop. I am already using quill in all my application processes and it's working fine but when I just add the 2 lines of code to set the log pattern it does give me an error during runtime. Quill is compiled and installed in /usr/local and im linking with library. Im using gcc 10.2 with flag c++17 in all my processes.

**Comment by odygrd** [comment]
I tried your example in my environment without any issues. 
`06/03/21 22:22:59.782121186 +0000 root example_custom_formatter.cpp:28 LOG_INFO      - The default logger is using a custom format
06/03/21 22:22:59.782168364 +0000 logger_foo example_custom_formatter.cpp:33 LOG_INFO      - The new logger is using the custom format`

I don't understand how it does not crash with the default pattern, but crashes when you set it manually
When you do _not_ call `set_pattern` it is still being called by the default ctor here :
https://github.com/odygrd/quill/blob/6cd23621307937d266034f51207b477b93f93001/quill/include/quill/PatternFormatter.h#L156


Is it a runtime error or a linker error ? 
The error you posted in the first post it looks like a linker error but in your second post you said that you are getting an error during runtime. Can you please maybe post me the stack trace if it is a runtime error or some more linker information if it is a linker error ? If it is a linker error and you have time maybe please try to demangle https://stackoverflow.com/questions/64122365/is-there-a-simple-way-to-have-ld-output-demangled-funtion-names

Can you try with something simple without any timestamp ?
` stdout_handler->set_pattern(QUILL_STRING("%(logger_name) LOG_%(level_name) - %(message)")); `

**Comment by fayce66** [comment]
Hello again, I did recompile my whole application from scratch and it finally works, this is strange that CLion did not complain during the link time. Finally all is good and I could set specific patterns for console and file handlers.

Thanks a lot for the help.

I said that already but great library! cheers.
