### ISSUE TITLE
Quill::Logger crashes on Windows 2016 and below version  of windows

### ISSUE THREAD

**Issue by anluoma** [odygrd/quill#113]
Just started to use Quill:logger and when we are trying to run it on windows 2016 or below versions it wont start. Reason probably is that quill uses API that does not work in those systems. 

See bug https://github.com/MicrosoftDocs/visualstudio-docs/issues/4124

Can make this use of SetThreadDescription conditional for those platform or use some other way?

**Comment by anluoma** [comment]
Tried to compile now against older windows sdk and it seems linker caught this as well:
 quill.lib(Os.cpp.obj) : error LNK2019: unresolved external symbol __imp_SetThreadDescription referenced in function "void __cdecl quill::detail::set_thread_name(char const *)" (?set_thread_name@detail@quill@@YAXPEBD@Z)

**Comment by anluoma** [comment]
By checking the docs from https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription it seems that this might work in 2016 version but only when using run time linking. 

If we don't set this all where does it affect?

**Comment by anluoma** [comment]
It seems that thread name support has been implemented in https://github.com/odygrd/quill/issues/97

**Comment by anluoma** [comment]
We could add feature flag for this or get info from windows api whether its supported but it with little investigation that might be little complicated.

```
void set_thread_name(char const* name)
{
  #if defined(__CYGWIN__) || defined(__MINGW32__) || defined(__MINGW64__) || defined(QUILL_NO_THREAD_NAME_SUPPORT)
  // Disabled on MINGW / Cygwin.
  (void)name;
#elif defined(_WIN32)
```

**Comment by odygrd** [comment]
Hey, thanks for reporting. 

I saw that in windows documentation when doing the implementation that's why I did put `Windows 10 - version 1607, Windows Server 2016` in the Readme. I was not expecting people to be using that old version of windows 

I think the easiest solution would be to add the `#if defined flag` that you are suggesting above. 

Could you please try locally to replace the code in `set_thread_name` with `(void)name;` and if you are not having any more issues I will add this

**Comment by anluoma** [comment]
Hi, 

There is also a note that you need to use run time dynamic linking in server 2016 version so current solution don't work directly there : 
"Windows Server 2016, Windows 10 LTSB 2016 and Windows 10 version 1607: SetThreadDescription is only available by Run Time Dynamic Linking in KernelBase.dll."

Check: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription

I'll try to check this on my local env.

**Comment by anluoma** [comment]
After compiling quill with the new flag (QUILL_NO_THREAD_NAME_SUPPORT) set to ON quill seems to work ok on windows 2012 R2 and windows 2016 and is able to log to console and file at least. 

If you specify thread name formatter like this [%(thread_name)], output will be just [].

**Comment by anluoma** [comment]
I am fine
