### ISSUE TITLE
Enumerate all loggers?

### ISSUE THREAD

**Issue by JohnGalbraith** [odygrd/quill#114]
Would it be possible to have a function that returns a list of all the loggers (or perhaps just their names) that have been created?  It appears that this information exists already, but is contained deep within Quill as private data in the `detail` namespace.  There might be a reason to protect these data that I don't know about, but if I could read them it would be handy.

Something like this:
`const std::vector<std::string> quill::get_all_logger_names();` 

One use case I have for this is to populate a webapp with these channels.  This already works (and is great) but I have to keep my own separate list of all the loggers that I have created.  It would be nifty to just query Quill natively for this information.

**Comment by odygrd** [comment]
yeah sure it can be done, adding it to todo items
