### ISSUE TITLE
Release build using nvcc crashes if dual queue mode is activated

### ISSUE THREAD

**Issue by TillAlex** [odygrd/quill#117]
I am observing a strange issue: When building a CUDA application using quill in Debug mode everything works fine. As soon as I switch to Release the application crashes with an access violation. The same application works fine, when not building with nvcc, but with MSVC. 

It is hard to debug this issue, because the application does not crash in Debug or RelWithDebInfo. Any ideas?

Some more information:
OS: Windows 10
MSVC: 19.28.29913.0
NVCC: 11.3.58

Stack when crashing:
<unknown> 0x00007ff67b4d567d
<unknown> 0x00007ff67b4d5045
<unknown> 0x00007ff67b4d366e
_configthreadlocale 0x00007ffbc1591bb2
BaseThreadInitThunk 0x00007ffbc21b7034
RtlUserThreadStart 0x00007ffbc3e82651

Attached you find a minimal reproducer:

[quill_nvcc.zip](https://github.com/odygrd/quill/files/6669873/quill_nvcc.zip)

**Comment by TillAlex** [comment]
Anyone able to reproduce this issue? Any ideas?

**Comment by TillAlex** [comment]
Did anyone try?

**Comment by TillAlex** [comment]
After some complicated debugging in release mode I found that this issue is connected to dual queue mode. After deactivating dual queue mode everything runs fine. I will see if I can find out what exactly is the problem...

**Comment by TillAlex** [comment]
It seems that in nvcc release mode get_serialization_metadata_ptr() is not called during initialization and therefore the pointer to the metadata is zero when the BackendWorker reads it from the queue. But why?

**Comment by oPiZiL** [comment]
GCC 7.5.0

**Comment by odygrd** [comment]
Sorry for the late response and thanks for reporting. There was some undefined behaviour reading this pointer that is fixed in `v1.7.0`.
I have never used nvcc before so please give it another try if you can, otherwise I will also try to reproduce in a few days

**Comment by TillAlex** [comment]
Good to know you are working on quill again. Thanks!

I am not able to reproduce the issue anymore. Not sure if this is because of your bugfix, updated nvcc or updated MSVC. Will close the issue...

**Comment by odygrd** [comment]
thanks for checking ! I think it was related to UB that was fixed here https://github.com/odygrd/quill/issues/166
