### ISSUE TITLE
How to right-align std::chrono::duration values?

### ISSUE THREAD

**Issue by ianloh** [odygrd/quill#118]
```cpp
using std::chrono;

// Prints "10ms"
QUILL_LOG_INFO(logger, "{}", 10ms);

// MSVC Error C3615 constexpr function 'fmt::v7::detail::parse_format_specs' cannot result in a constant expression
QUILL_LOG_INFO(logger, "{:>6}", 10ms);
```    
For what it's worth, `fmtlib` does support the second syntax.

Edit: added syntax highlighting

**Comment by odygrd** [comment]
Hello, it looks like that was a libfmt syntax ? I have tested the above code on vs2022 and on gcc and it compiles and aligns it as expected.
Please reopen if the issue persits
