### ISSUE TITLE
{fmt} v8.0.0

### ISSUE THREAD

**Issue by bl-ue** [odygrd/quill#119]
{fmt} 8 was released 🎉 — please consider upgrading to it.
https://github.com/fmtlib/fmt/releases/tag/8.0.0

**Comment by odygrd** [comment]
Hey, will do so over the next few weeks. Waiting for a few more days in case there is an `8.1.0` release or so..

**Comment by mathisloge** [comment]
It would be cool to have a release, since the update at vcpkg holds because the latest release from quill isn't compitable.  And therefore also holds spdlog and fmt
https://github.com/microsoft/vcpkg/pull/18581

**Comment by odygrd** [comment]
Sorry for the late turnaround. There is now release v1.6.3
