### ISSUE TITLE
Missing Documentation for Function Arguments

### ISSUE THREAD

**Issue by jwillikers** [odygrd/quill#12]
When compiling with Clang's "-Wdocumentation" flag, there is a slew of warnings output for Doxygen documentation for function arguments which are missing documentation strings. I would like to have these warnings treated as errors when compiling my application, but the included headers cause my build to fail. I can ignore the warning for now, but would it be possible to either remove the undocumented function parameters or document them to fix this warning?

**Comment by odygrd** [comment]
Hey, thanks for feedback, yes will fix this very soon

**Comment by jwillikers** [comment]
Much appreciated 👍👍
