### ISSUE TITLE
warning: implicit dereference will not access object of type ‘volatile'

### ISSUE THREAD

**Issue by fayce66** [odygrd/quill#120]
Hello, during compile I always have the following warning (gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0):

**rocket/rocket.hpp: In member function ‘void rocket::detail::connection_base<rocket::thread_safe_policy>::disconnect()’:
rocket/rocket.hpp:2074:81: warning: implicit dereference will not access object of type ‘volatile rocket::intrusive_ptr<rocket::detail::connection_base<rocket::thread_safe_policy> >’ in statement
 2074 |                     static_cast<intrusive_ptr<connection_base> volatile&>(prev) = nullptr;**

Is this something I should worry about? Is there a way to fix and remove that warning?

Thanks for the great library.

**Comment by odygrd** [comment]
Hello, can you please double check if this warning is coming from quill or your code ?
If possible can you post a small sample that is producing this warning ?

**Comment by fayce66** [comment]
I just took your library header and copied the whole content in compiler explorer, and tried your first example at the top of the header, and compiler explorer gives me exactly the same warning...

**Comment by odygrd** [comment]
I am not sure which header you are talking about, is that about quill or is it about rocket/rocket.hpp header ? please elaborate
