### ISSUE TITLE
[FR] mode for force flush & traceback for crash

### ISSUE THREAD

**Issue by sjyMystery** [odygrd/quill#125]
It's important for some cases when you need debug for segmentation fault.
Nor you will never get the Information for some crashes like segmentation faults.
We can make it an opional.

**Comment by odygrd** [comment]
There is already a force flush on crash if you enable the signal handler. see https://github.com/odygrd/quill/blob/master/examples/example_signal_handler.cpp

It is not easy to provide cross platform traceback support for all 3 compilers .. it is simple to get the traceback by running the debugger

**Comment by odygrd** [comment]
Closing this for now as there are no plans to provide traceback at the moment. As explained above force flush already exists via the signal handler.
