### ISSUE TITLE
non intrusive solution for marking safe to copy loggable

### ISSUE THREAD

**Issue by zhuoqiang** [odygrd/quill#132]
while `QUILL_COPY_LOGGABLE` could enable the user defined type to be copy loggable, however it is an intrusive solution that requires the class to be modified.

Would like to have an non intrusive solution that could mark 3rd party classes to be safe to copy loggable.

**Comment by odygrd** [comment]
Hello, I understand your requirement. However, for 3rd party classes to be logged they should also have `operator<<` defined. 

A workaround for now would be to wrap them into you own class (where you can add QUILL_COPY_LOGGABLE and also `operator<<` if it is missing) and derive publicly from them and use your own wrapper instead.

**Comment by zhuoqiang** [comment]
thanks for providing the workaroud solution.

I think a non intrusive solution is useful even for code that you could modify.

usually class definition is shared and used for many, and the intrusive `QUILL_COPY_LOGGABLE` would introduce quill dependency to all users of that class.

On the other hand, `operator<<` is non intrusive. user could add it later and they do not have to include iostream just for using that class. I think there are plenty of non-intrusive solution in std and other 3rd party libs (using template specilization, etc)

**Comment by odygrd** [comment]
The macro doesn’t introduce any dependency to Quill. It expands to 
using copy_loggable = std::true_type
so you can use that instead.

It’s not possible to introspec the class members of each class for pointers or other unsafe to copy types

I’m not aware of a better solution for now to protect the users from accidentally copying unsafe types.

The check can also be disabled if you use QUIL_MODE_UNSAFE

if you have any better ideas please share with a small example

**Comment by zhuoqiang** [comment]
thanks for the response, here's some thoughts on the non-instrusive solution:

```c++
// suppose class Meter is a 3rd party lib
namespace Some3rdPartyLib {

struct Meter {
  int value;
};

// it has well-defined streamm method
std::ostream<<(std::ostream& out, const Meter&);

}

Some3rdPartyLib::Meter height{3};

// since we could not modify 3rd party lib, we have to log it this way:
// it has 2 drawbacks:
// - verbose using to_string()
// - inefficency, converting to string happens in working thread not logging thread
LOG_INFO("the height is {}", to_string(height));

// what if we have a dedicated non-intrusive trait
// to let quill know that it could be copied and convert to string later in logging thread
// basiclly same as QUILL_COPY_LOGGABLE, but defined outside the class

template<class T>
struct is_copyable_for_quill : std::false_type {};

template<>
struct is_copyable_for_quill<Some3rdPartyLib::Meter> : std::true_type {};
```

there's also something similar in stdlib: https://en.cppreference.com/w/cpp/types/is_trivially_copyable

another solution would be providing a customization point for `copying` the object into logging thread:

```c++
// this is the basic fallback solution for all types
template<class T>
std::string to_quill_object(const T& t) {
  return to_string(t);
}

// could be override for specific type
Meter to_quill_object(Meter meter) {
  return meter;
}

// or a bunch of types using enable_if / concept
template<TriviallyCopyable Copyable>
auto to_quill_object(Copyable obj) {
  return obj;
}
```

**Comment by odygrd** [comment]
Thanks for the suggestion, I do agree that a non intrusive solution is better. This is added in 545aec60ecebff459794effce7e1d5f81c23905c 

The example is also updated https://github.com/odygrd/quill/blob/master/examples/example_user_defined_types.cpp#L81

**Comment by zhuoqiang** [comment]
thanks for the quick enhancement. could not wait to see the updated release in conan :)
