### ISSUE TITLE
remove LOG_ prefix to log level_name / add %(level_id) placeholder

### ISSUE THREAD

**Issue by zhuoqiang** [odygrd/quill#136]
for `%(level_name)` placeholder, it seems redundent to include the `LOG_` prefix to the log level.

Would like to have `DEBUG` instead of `LOG_DEBUG` in the log output as the level name.

or for backward compatible consideration, could we add a new placeholder, like `%(level)` or something. It would be nice to have user defined placeholder, but that's beyond this issue ...

**Comment by yesudeep** [comment]
I'd recommend adding 1 more log level placeholder variable in addition to this:

%(level_name) = DEBUG, ERROR, etc.
%(level_name_short) = D,E,W,C,I,T1,T2,T3

**Comment by odygrd** [comment]
hello @zhuoqiang , as already been said `%(level_name)` will only add `INFO` .. The prefix `LOG_` is added by quill's default pattern. You can change the pattern and set a custom one as in this example (https://github.com/odygrd/quill/blob/master/examples/example_custom_formatter.cpp) without the prefix. 
Also see https://github.com/odygrd/quill/wiki/4.-Formatters

I think it would be straightforward to add `level_id` i will try to add it to master
