### ISSUE TITLE
cannot rotate log files when it reaches the max backup count

### ISSUE THREAD

**Issue by BluewareJ** [odygrd/quill#157]
I know it's by design so far, but it may leading to infinite size of log file.
so, when it reaches the max backup file count, how about removing the the oldest backup file, and then backup current log file?
it's better to enable this behavior by passing a flag to RotatingFileHandler constructor.
how do you think? thanks.

**Comment by odygrd** [comment]
this is fixed now in master, thanks for reporting ! if you have any more issues please let me know
