### ISSUE TITLE
create logger with handler iterators

### ISSUE THREAD

**Issue by BluewareJ** [odygrd/quill#158]
I'd like to create_logger with multiple handlers using iterators, so I add a new I/F as below:
  template &lt;class Iter&gt;
  Logger* create_logger(char const* logger_name, Iter firstHandler, Iter lastHandler);

It works for std::initialize_list<Handler*>().begin() and end(), but failed to link with unresolved symbol for std::vector<Handler*>().begin() and end(), it seems std::vector<Handler*>::const_iterator is not defined. 
But if I add a new I/F and implement as below, then vector iterator works, do you know why? thanks.
  Logger* create_logger(char const* logger_name, const std::vector<Handler*>& handlers)
  {
      return create_logger(logger_name, handlers.begin(), handlers.end());
  }

Note: I compile it on Windows with VS2019 cmake.

**Comment by odygrd** [comment]
I am closing this as when https://github.com/odygrd/quill/pull/182 an new function has been added to the API when creating a logger that allows you to pass a `std::vector<Handler>`. That should be in version `v2.1.0`
Please open a new ticket if you notice any other issues !
