### ISSUE TITLE
Minimal structured logging

### ISSUE THREAD

**Issue by smahapatra1** [odygrd/quill#159]
Please do a Google search for 'minimal structured logging for autonomous vehicles' video in cppcon 2019. Quill seems to be already using the best ideas of that talk but if can support structured logging like that video (Python structlog package is another motivation), it will be fantastic.

**Comment by odygrd** [comment]
Hello, Quill is not designed to support `minimal` style logging. It produces the final human readable file directly. However, it is possible to produce a structure log without compromising any performance.
To enable structured logging, named arguments have to be provided to the initial format string. https://github.com/odygrd/quill/pull/184 is meant to add support for producing a JSON log file
