### ISSUE TITLE
windows macro for log template

### ISSUE THREAD

**Issue by P-yver** [odygrd/quill#161]
Hi,
I am trying to use macro to define my log messages, here is a basic sample to reproduce the issue:

```
#include "quill/Quill.h"

#define _PREFIX "[Init] "
#define MSG_CONCAT "{} Message", _PREFIX

int main()
{
  quill::start();
  LOG_INFO(quill::get_logger(),  "{} Message", _PREFIX);
  LOG_INFO(quill::get_logger(), MSG_CONCAT);
  return 0;
}
```

It works as expected under Ubuntu, but the second entry throw compilation error under Windows (vs2019).
Do you have any suggestions?

(Edit: the second entry is intended to be similar to the first one)

**Comment by P-yver** [comment]
Errors are:
```
error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'quill::LogMacroMetadata'
error C3615: constexpr function 'main::<unnamed-tag>::operator ()' cannot result in a constant expression
error C2672: 'fmt::v8::detail_exported::compile_string_to_view': no matching overloaded function found
error C2780: 'fmt::v8::basic_string_view<Char> fmt::v8::detail_exported::compile_string_to_view(fmt::v8::detail::std_string_view<T>)': expects 1 arguments - 2 provided
error C2780: 'fmt::v8::basic_string_view<Char> fmt::v8::detail_exported::compile_string_to_view(const Char (&)[N])': expects 1 arguments - 2 provided
error C3615: constexpr function 'main::<lambda_2170bb369b4e25ff2c14cb6158ed2497>::()::FMT_COMPILE_STRING::operator fmt::v8::basic_string_view<char>' cannot result in a constant expression
```

**Comment by odygrd** [comment]
looks like msvc is treating `MSG_CONCAT` as an initializer_list.

The following seems to be working

`#include "quill/Quill.h"

#define _PREFIX "[Init] "
#define MSG_CONCAT "{} Message " _PREFIX

int main()
{
  quill::start();
  LOG_INFO(quill::get_logger(), "{} Message", _PREFIX);
  LOG_INFO(quill::get_logger(), MSG_CONCAT, "test");

  return 0;
}`

Closing for now. If you have any other issues let me know
