### ISSUE TITLE
no quill.lib generated in visual studio 2022

### ISSUE THREAD

**Issue by DanielKui** [odygrd/quill#170]
I only got quill.dll by _cmake -DCMAKE_PREFIX_PATH=D:\fmt-8.0.1\fmt-8.0.1 -DQUILL_FMT_EXTERNAL=ON -DBUILD_SHARED_LIBS=ON -DQUILL_NO_THREAD_NAME_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=./_

no quill.lib,  I wanna use quill dynamic library both quill.dll and quill.lib in windows platform.

Now only quill.dll generated.

**Comment by odygrd** [comment]
hello,

quill is generating one library each time based on DBUILD_SHARED_LIBS value. 

On linux you can run the command twice like this to build and install both :

for shared :

```
cmake -DCMAKE_PREFIX_PATH=D:\fmt-8.0.1\fmt-8.0.1 -DQUILL_FMT_EXTERNAL=ON -DBUILD_SHARED_LIBS=ON -DQUILL_NO_THREAD_NAME_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=./

make install
```

then for static

```
cmake -DCMAKE_PREFIX_PATH=D:\fmt-8.0.1\fmt-8.0.1 -DQUILL_FMT_EXTERNAL=ON -DBUILD_SHARED_LIBS=OFF -DQUILL_NO_THREAD_NAME_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=./

make install
```

Could you do something equivalent on windows ?

If that is not enough you can manually edit the cmake file to explicitly generate both libraries [here](https://github.com/odygrd/quill/blob/master/quill/CMakeLists.txt#L141)
