### ISSUE TITLE
gcc7.5 compile error: error: filesystem: No such file or directory #include <filesystem>

### ISSUE THREAD

**Issue by oPiZiL** [odygrd/quill#178]
GCC v7 still does not implement [<filesystem>](https://en.cppreference.com/w/cpp/header/filesystem) but it does have the Filesystem Technical Specification which is in [<experimental/filesystem>](https://en.cppreference.com/w/cpp/header/experimental/filesystem)

**Comment by oPiZiL** [comment]
try to fix it #179

**Comment by odygrd** [comment]
thanks for reporting and the PR, now merged in master (https://github.com/odygrd/quill/pull/181) 
Please report if you see any issues
