### ISSUE TITLE
Undefined Behavior detected by Sanitizers

### ISSUE THREAD

**Issue by alphanso** [odygrd/quill#180]
I am using quill v1.7.3

..../quill/detail/spsc_queue/BoundedSPSCEventQueue.h:282:13: runtime error: applying non-zero offset 160 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ..../quill/detail/spsc_queue/BoundedSPSCEventQueue.h:282:13 in
.../quill/detail/spsc_queue/BoundedSPSCRawQueue.h:66:45: runtime error: applying non-zero offset 131072 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior .../headers/quill/detail/spsc_queue/BoundedSPSCRawQueue.h:66:45 in

**Comment by odygrd** [comment]
hey, thanks for reporting. Would it be possible to post a reproducible example ? I have not seen this UB message by the sanitizers before

**Comment by odygrd** [comment]
Thanks for updating, what option did you change specifically?

**Comment by alphanso** [comment]
I was using bounded queue with dual queue mode. I was passing it via command line build script. While debugging it was still calling some unbounded queue event. I realized maybe I am not passing options properly. So I removed them and added them via TweakMe config. I didn't face any issue after that.
