### ISSUE TITLE
Interface for notifying that quill drops a log?

### ISSUE THREAD

**Issue by mudream4869** [odygrd/quill#186]
In non-guarantee-mode, is there any interface for notifying user (ex: pass a callback function?) when quill is dropping a log?

**Comment by odygrd** [comment]
hello, in the non-guarantee-mode there is a counter of how many messages are being dropped, the backend thread that is doing the formatting and the logging also checks that counter and if there are any dropped logs it will log a statement to `stderr` ( [see here](https://github.com/odygrd/quill/blob/6eb75111b7059ec861da8524923dc0750ea561bb/quill/src/detail/backend/BackendWorker.cpp#L70) )

At the moment it just logs to `stderr` it is not possible to control it via a callback, do you have some use case where a callback would be useful or are you okay getting them in `stderr`  ?
