### ISSUE TITLE
Add QUILL_SHOULD_LOG macro

### ISSUE THREAD

**Issue by fhriley** [odygrd/quill#187]
Currently, to conditionally do some processing before logging, you do it like this:

```c++
if (logger->should_log(LogLevel::TraceL1)) {
  ... // do some processing
  LOG_TRACE_L1(logger, ...);
}
```

If `QUILL_ACTIVE_LOG_LEVEL` is set to `QUILL_LOG_LEVEL_DEBUG` or higher, the `LOG_TRACE_L1` will not be compiled in, but the remaining code will be. It seems like there should be a macro instead such that the code above becomes:

```c++
if (QUILL_SHOULD_LOG(logger, LogLevel::TraceL1)) {
  ... // do some processing
  LOG_TRACE_L1(logger, ...);
}
```

The macro would just evaluate to `false` when `QUILL_ACTIVE_LOG_LEVEL` is set to `QUILL_LOG_LEVEL_DEBUG` or higher.

**Comment by odygrd** [comment]
hello, thanks for reporting.

A compile time check has been added to `logger->should_log<level>()` 

previous `logger->should_log(level)` has now been removed to avoid confusion. 

The below should have equivalent behaviour to the requested SHOULD_LOG macro :
```c++
if (logger->should_log<LogLevel::TraceL1>()) {
  ... // do some processing
  LOG_TRACE_L1(logger, ...);
}```
