### ISSUE TITLE
Bad allocation exception after set_pattern call using timestamp format from docs/examples

### ISSUE THREAD

**Issue by wusikijeronii** [odygrd/quill#200]
**OS:** Windows 11
**Compiler:** gcc version 12.2.0 (Rev4, Built by MSYS2 project)
**Description**:
Hello.
Today I tried this library. If I call set_pattern from a file handler using examples from docs or code from examples folder in the repository, I get a bad_alloc exception. Example:
```c++
 // Get the stdout file handler
  quill::Handler* file_handler = quill::stdout_handler();

  // Set a custom formatter for this handler
  file_handler->set_pattern("%(ascii_time) [%(process)] [%(thread)] %(logger_name) - %(message)", // format
                            "%D %H:%M:%S.%Qms %z",     // timestamp format
                            quill::Timezone::GmtTime); // timestamp's timezone
```

But if I change the timestamp format to `%H:%M:%S.%Qns` (I saw this string from `PatterFormatter.h`) everything works successfully. 
For building my app, I use cmake with the 23 CXX standard.
And one more ask - can you fix the docs in the wiki? At the very least, the definitions `QUILL_STRING`and `set_default_logger_handler` do not appear to exist.

Seems, I forget to add a main question. Why I get a bad_alloc error? Is the code [here](https://github.com/odygrd/quill/blob/master/examples/example_custom_formatter.cpp) deprecated?

**Comment by odygrd** [comment]
Hello, thanks for reporting. The wiki is slightly out of date as the library as evolved, I will update it.

All the examples in the examples folder are up to date.  example_custom_formatter.cpp works with MSVC compiler on windows. 

All the arguments that you pass as timestamp format expect the `Qms Qns` in  `"%D %H:%M:%S.%Qms %z"` are passed to `strftime(...)` as format argument,  in that case it is passed `"%D %H:%M:%S %z"`

It seems that you are using MinGW and it is known that `stftime(...)` doesn't support all format arguments for MinGW

You can try with the following minimal example https://cplusplus.com/reference/ctime/strftime/ to see which format specifier is not supported in MinGW, it will probably be either `%D` or `%z` 
e.g. pass to `strftime(...)` as format `%D %H:%M:%S %z` and then try to remove a format specifier `%D %H:%M:%S`

**Comment by wusikijeronii** [comment]
Thank you. I have understood.

**Comment by odygrd** [comment]
you are welcome :) 
I have updated the out of date wiki parts and also added a note about MinGW
