### ISSUE TITLE
Vcpkg install - Linking issues

### ISSUE THREAD

**Issue by Chuangy** [odygrd/quill#210]
Hi,

Thanks for library! Quill seems just like the solution I need for logging outside the hot-path.
I just came across a strange (linking?) issue when installing via vcpkg. I have the following minimalistic example with CMakeLists.txt as such:

```
find_package(quill CONFIG REQUIRED)
add_executable(quill_test quill_test.cpp)
target_link_libraries(quill_test PRIVATE quill::quill)
```

Then in the `quill_test.cpp`, I have a very simple
```
#include "quill/Quill.h"

int main() {
    quill::Handler* fhandler = quill::file_handler("test.log", "w");
    return 0;
}
```

When trying to build, I get the following error:
```
[build] quill_test.cpp:(.text.startup+0xab): undefined reference to `quill::file_handler(std::filesystem::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, quill::FilenameAppend)'
```

Other methods such as `quill::start` or `quill::get_logger` and macros like `LOG_INFO` all seem to work fine - it just seems to be the `quill::file_handler` which has linking issues. 

I have tried reinstalling through vcpkg but doesn't seem like it fixes this. I was wondering if I could get some help with the setup or if there is anything I've missed.

Regards

**Comment by odygrd** [comment]
Hello, are you using visual studio ?

I just tried and I could not reproduce. Steps I've followed

```
.\vcpkg.exe install quill --triplet x64
.\vcpkg.exe integrate install
```

Then start a new VS project.

Edit CMakePresets.json `configurePresets` and added

```
...
          "cacheVariables": {
            "CMAKE_C_COMPILER": "cl.exe",
            "CMAKE_CXX_COMPILER": "cl.exe",
            "CMAKE_TOOLCHAIN_FILE": {
              "value": "C:/Users/odygr/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake",
              "type": "FILEPATH"
            }
...
```

Then the following compiled and runs :

<img width="1850" alt="image" src="https://user-images.githubusercontent.com/7397786/205521768-c7af1c6b-fe2c-49b9-a0eb-cef4a7b99e3f.png">

I have also tried the x64 Release build and it also works. Can you maybe retry by following the above steps ?

**Comment by Chuangy** [comment]
Hi,

Thanks for taking a look into it. I am currently using Ubuntu, compiling with gcc. I have retried the above steps again (attached photo)
![image](https://user-images.githubusercontent.com/30322689/205658722-ca577ece-e096-4fd7-9953-5b1393168848.png)
I unfortunately still end up with the same error at the linking stage.

Regards

**Comment by odygrd** [comment]
I tried on my Ubuntu. I installed vcpkg and then I installed the x64-linux triplet. and I still can not reproduce : ( 
It is weird seeing a link error as there are plenty on github actions jobs on Ubuntu 18.04 and 20.04 and all are passing 

What is your Ubuntu version ?

![image](https://user-images.githubusercontent.com/7397786/205767330-4f034843-a871-4f57-aa00-7f2080054c66.png)

Can you try to compile it on the command line directly by running

```
mkdir build
cd build
/usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/home/alpha/Documents/prog/vcpkg/scripts/buildsystems/vcpkg.cmake ..
```

**Comment by Chuangy** [comment]
Ahhh, thanks for that! 

You were correct - I get the following symbols in the quill build object which indeed shows that its using the `std::experimental::filesystem` library.

```
$ objdump -t ../vcpkg/packages/quill_x64-linux/lib/libquill.a | c++filt | grep "file_handler"
0000000000000529 g     F .text.unlikely 00000000000000ae quill::file_handler(std::experimental::filesystem::v1::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, quill::FilenameAppend)
00000000000005d7 g     F .text.unlikely 000000000000026d quill::time_rotating_file_handler(std::experimental::filesystem::v1::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, quill::Timezone, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000844 g     F .text.unlikely 0000000000000242 quill::rotating_file_handler(std::experimental::filesystem::v1::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned int, bool)
```
After a reinstall of quill using the same versions of  `gcc` and `g++` as what I am trying to compile with, the linking works for me! I ran the following
```
$ ./vcpkg remove quill
$ export CC=/usr/bin/x86_64-linux-gnu-gcc-9 
$ export CXX=/usr/bin/x86_64-linux-gnu-g++-9
$ ./vcpkg install quill
```
and the link succeeeded. The new symbols of the new build now have
```
$ objdump -t packages/quill_x64-linux/lib/libquill.a | c++filt | grep "file_handler" 
00000000000009bb g     F .text.unlikely 00000000000000ab quill::file_handler(std::filesystem::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, quill::FilenameAppend)
0000000000000a66 g     F .text.unlikely 0000000000000334 quill::time_rotating_file_handler(std::filesystem::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, quill::Timezone, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000d9a g     F .text.unlikely 00000000000002a8 quill::rotating_file_handler(std::filesystem::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned int, bool)
```
which are now consistent with those in the header file.

Thanks so much for taking a look - I had forgotten about the existence of `objdump`.
