### ISSUE TITLE
Conflicting declaration of strlen with Mingw-w64

### ISSUE THREAD

**Issue by jwillikers** [odygrd/quill#22]
There is a conflicting declaration of the function `strlen` with C-Linkage when compiling with Mingw-w64 on Windows 10.
This occurs in version v1.2.3 and on the most recent commit a4ae2966783ce24946fd314508ba328f4964bd11.
The compiler error is as follows.
```console
C:/msys64/mingw64/x86_64-w64-mingw32/include/intrin.h:269:5: error: conflicting declaration of 'size_t quill::detail::strlen(const char*)' with 'C' linkage
  269 |     __MACHINE(size_t __cdecl strlen(const char *))
      |     ^~~~~~~~~
compilation terminated due to -Wfatal-errors.
```
The conflicting function is defined in [Utilities.h](https://github.com/odygrd/quill/blob/ba7c73dcc021ad73cb9869f1af978636c919820c/quill/include/quill/detail/misc/Utilities.h).

**Comment by odygrd** [comment]
Thanks for reporting. I renamed the function, can you try again and confirm please ?

**Comment by jwillikers** [comment]
Everything builds on Mingw-w64 👏 using the latest commit, eb56fe845b0df0df9a87ce2c7f1a14e9e76de581. Thanks @odygrd
