### ISSUE TITLE
QUILL_FMT_EXTERNAL causes an empty dir to be installed

### ISSUE THREAD

**Issue by tocic** [odygrd/quill#220]
When using the externally installed `fmt` library, you will have an empty directory called `bundled` in the resulting package since the following command ignores only `bundled/fmt`, not `bundled` itself.

https://github.com/odygrd/quill/blob/476467f070324b864124084d27f5b28e71c88adb/quill/CMakeLists.txt#L244-L246

**Comment by odygrd** [comment]
thanks for reporting, I have now fixed this in master
