### ISSUE TITLE
Release build keeps build dir refs in the resulting library 

### ISSUE THREAD

**Issue by tocic** [odygrd/quill#221]
```bash
git clone https://github.com/odygrd/quill.git
cd "quill/"
mkdir "build/"
cmake -B "build/" -S .
cmake --build "build/"
strings "build/quill/libquill.a" | grep "tocic"
```

results in 

```
/home/tocic/quill/quill/src/detail/SignalHandler.cpp
/home/tocic/quill/quill/include/quill/detail/LogManager.h
```

, i.e. the library contains references to its build directory. I think the release version should not contain them for reproducibility.

The first line seems to be the result of expanding

https://github.com/odygrd/quill/blob/c5c931d012c4e8e88d25cb8def5c84868537a4cf/quill/src/detail/SignalHandler.cpp#L232

to

https://github.com/odygrd/quill/blob/0f268ba6c80d047bca32c7f5a5978a3a9bdb4c81/quill/include/quill/detail/LogMacros.h#L50

**Comment by odygrd** [comment]
Thanks for reporting, I also believe the reason is it stores the metadata of the log line and that is the location of the file etc in compile time. 
I will have a look over the next few days and remove the metadata from this log message

**Comment by odygrd** [comment]
a fix for this will be in master soon, if you see anything else that needs fixing let me know
