### ISSUE TITLE
Ordering of log messages with identical timestamp

### ISSUE THREAD

**Issue by aboulart** [odygrd/quill#223]
When using a custom clock for simulated time, it's possible for multiple log events from 1 thread to have exactly the same timestamp.

They then get re-sorted by the backend worker thread, which doesn't maintain relative ordering of events retrieved from the same queue. So sequential events from 1 thread appear in a different order, which seems wrong.

A simple fix is to add a sequence number to the key of the std::priority_queue used for re-ordering events.

**Comment by odygrd** [comment]
Thanks a lot for reporting this
