### ISSUE TITLE
Quill 1.2.2 includes intrinsic headers in its own namespace

### ISSUE THREAD

**Issue by BRevzin** [odygrd/quill#23]
Recent changes mean that Rtdsc.h now does something [like this](https://github.com/odygrd/quill/blob/eb56fe845b0df0df9a87ce2c7f1a14e9e76de581/quill/include/quill/detail/misc/Rdtsc.h#L55):

```cpp
namespace quill::detail {
#include <x86intrin.h>
}
```

Which can break name lookup in all sorts of weird contexts. Can you do the includes outside of the namespace?

**Comment by odygrd** [comment]
Thanks for reporting this, fixed
