### ISSUE TITLE
fs::rename throw an exception in gcc7.5.0

### ISSUE THREAD

**Issue by oPiZiL** [odygrd/quill#230]
https://github.com/odygrd/quill/blob/master/quill/src/detail/misc/FileUtilities.cpp#L62

**Comment by odygrd** [comment]
Hello, is that when the RotatingFileHandler is used ? Could you let me know what exception ? 

any way to reproduce?

**Comment by odygrd** [comment]
I think you mean that the function shouldn't be marked as noexcept, thanks for reporting this
