### ISSUE TITLE
BoundedQueue improvement 

### ISSUE THREAD

**Issue by ksergey** [odygrd/quill#243]
Hi!

Instead of allocating x2 memory inside [BoundedQueue](https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/spsc_queue/BoundedQueue.h#L37) you could `mmap(...)` the same memory region twice:

```c++
  std::size_t const size = ...;
  int fd = memfd_create(...);
  ftruncate(fd, size);

  auto address = ::mmap(nullptr, size << 1, PROT_NONE, MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
  if (address == MAP_FAILED) {
    throw ...;
  }
  data_ = static_cast<char*>(address);

  address = ::mmap(data_, size, PROT_READ | PROT_WRITE, MAP_FIXED | MAP_SHARED, fd, 0);
  if (address != data_) {
    throw ...;
  }

  address = ::mmap(data_ + size, size, PROT_READ | PROT_WRITE, MAP_FIXED | MAP_SHARED, fd, 0);
  if (address != data_ + size) {
    throw ...;
  }

  capacity_ = size;
  mask_ = capacity_ - 1;
```

The technique called `magic ring buffer`.

BTW nice logger!

Thanks

**Comment by takohack** [comment]
Hey,Bro. I am curious about Why autor need allocating **x2 memory** inside BoundQueue? Can we only allocate x1 memory?

**Comment by odygrd** [comment]
thanks for letting me know. I fixed it here and also made some improvements. It's mainly cosmetic changes and small things. 

https://github.com/odygrd/quill/pull/362/files

Throughput is about the same as old version:

old: Throughput is 2.21 million msgs/sec average, total time elapsed: 1809 ms for 4000000 log messages

new: Throughput is 2.24 million msgs/sec average, total time elapsed: 1787 ms for 4000000 log messages
