### ISSUE TITLE
C++17 Deprecation errors when building with Visual Studio 2017

### ISSUE THREAD

**Issue by dasigvr** [odygrd/quill#245]
I'm trying to compile quill with Visual Studio 2017 and I get this error from the compiler:

```
src\quill\detail\misc\utilities.cpp(17): error C4996: 'std::wstring_convert<convert_t,wchar_t,std::allocator<wchar_t>,std::allocator<char>>': warning STL4017: std::wbuffer_convert, std::wstring_convert, and the <codecvt> header (containing std::codecvt_mode, std::codecvt_utf8, std::codecvt_utf16, and std::codecvt_utf8_utf16) are deprecated in C++17. (The std::codecvt class template is NOT deprecated.) The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead. You can define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```

Adding the suggested directives do actually silence the error, nonetheless is this something I should be concerned with?

**Comment by odygrd** [comment]
hello, those are used only when you are logging wide strings. They are deprecated but still usable. There is nothing to worry about, in fact those warnings are still there but disabled in the CMake (https://github.com/odygrd/quill/blob/master/quill/CMakeLists.txt#L195)

There are CI builds for VS2019 and VS2022 (https://github.com/odygrd/quill/actions/runs/4069406913). I haven't tried quill with VS2017 but as long as it compiles it should be good.
