### ISSUE TITLE
Cant build quill on Centos 7, gcc 7.3.1, used to work fine a few days ago

### ISSUE THREAD

**Issue by mbhardwa** [odygrd/quill#246]
Hi , i started using Quill and wanted to deploy to prod, but with the latest git pull I cant seem to build it . i am able to buil and link with libquill in my separate standalone program
Some recent cmake related changes maybe ??
Thoughts ??
-----------------------------------------------
cd /home/mbhardwaj/work/tt.git/Falgo/quill/build/examples && /usr/local/cmake-3.25.2-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/example_backtrace.dir/link.txt --verbose=1
/opt/rh/devtoolset-7/root/usr/bin/gcc   -g -O3 -DNDEBUG CMakeFiles/example_backtrace.dir/example_backtrace.cpp.o -o example_backtrace  ../quill/libquill.a -lpthread -lstdc++fs
CMakeFiles/example_backtrace.dir/example_backtrace.cpp.o: In function `__gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*)':
/opt/rh/devtoolset-7/root/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
CMakeFiles/example_backtrace.dir/example_backtrace.cpp.o: In function `std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)':
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:1002: undefined reference to `std::__throw_length_error(char const*)'
.....
CMakeFiles/example_backtrace.dir/example_backtrace.cpp.o: In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<quill::detail::BackendWorker::run()::{lambda()#1}> > >::~_State_impl()':
/opt/rh/devtoolset-7/root/usr/include/c++/7/thread:178: undefined reference to `std::thread::_State::~_State()'
CMakeFiles/example_backtrace.dir/example_backtrace.cpp.o: In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<quill::detail::BackendWorker::run()::{lambda()#1}> > >::~_State_impl()':
/opt/rh/devtoolset-7/root/usr/include/c++/7/thread:178: undefined reference to `std::thread::_State::~_State()'

**Comment by mbhardwa** [comment]
The problem seems to be in building the examples

**Comment by odygrd** [comment]
hey, I tested that version on centos 7 before releasing it because I knew you are using it. I just tried to pull master and compiled without issues at centos 7 with gcc 7.3. I also ran the examples without issues.

I remember you were building quill without exceptions. Can that be related ? if libquill.a was build with some custom flags try to pass the same on the examples.

Let me know

**Comment by odygrd** [comment]
my build command is 

`cd /home/centos/git/build/quill && /opt/rh/devtoolset-7/root/usr/bin/c++  -I/home/centos/git/quill/include -I/home/centos/git/quill -O3 -DNDEBUG -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -Wno-unused-private-field -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-parameter -std=gnu++1z -MD -MT`

**Comment by odygrd** [comment]
seems like your above build command is using `gcc` instead you should be using `g++`

also see : 

https://stackoverflow.com/questions/27390078/gcc-compiling-c-code-undefined-reference-to-operator-newunsigned-long-lon

**Comment by odygrd** [comment]
closing this for now, please re-open if you still have any issues

**Comment by mbhardwa** [comment]
You can mark it closed. I will try with adding flags to build examples, I mean the no exception etc

Sent from my iPhone

On Feb 20, 2023, at 6:47 PM, Odysseas Georgoudis ***@***.***> wrote:

﻿

closing this for now, please re-open if you still have any issues

**Comment by odygrd** [comment]
thanks, let me know if any issues
