### ISSUE TITLE
[question] QUILL_ACTIVE_LOG_LEVEL in imported external lib ?

### ISSUE THREAD

**Issue by ZiperRom1** [odygrd/quill#254]
Hello,

I'm new using this logger lib and I didn't manage to setup `QUILL_ACTIVE_LOG_LEVEL` at compile time with any cmake flags like `-DCMAKE_CXX_FLAGS="-DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_DEBUG"` or `add_compile_definitions(QUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_DEBUG)` in CMakeFile.

The project log level is set on `QUILL_LOG_LEVEL_INFO` by defaut, if I do not explicitely call `logger->set_log_level(quill::LogLevel::Debug);` the `LOG_DEBUG` macros do not print.

I have a Logger singleton class which is initializing QuillLogger and this class is compiled as a static library and linked with a static `quill::quil` as a target of `find_package(quill CONFIG REQUIRED)` (manually compiled in my docker env).

Then I use the logger in others services with the following :

```c++
#include "Logger.hpp" // My singleton class
// ...
using Logger = Logger::Quill;
// ...
LOG_DEBUG(Logger::getLogger(), "Some debug {}", someVar);
```

Is `QUILL_ACTIVE_LOG_LEVEL` only available in compile time with in project build and not external ?

**Comment by odygrd** [comment]
`QUILL_ACTIVE_LOG_LEVEL` is only used in a header file : 
https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/LogMacros.h

it is defaulted here 
https://github.com/odygrd/quill/blob/1e78730dc142edad4a981991b7309ce65d9bdaf0/quill/include/quill/detail/misc/Common.h#L29

It should work. I will also give it a try over the next few days and let you know

**Comment by odygrd** [comment]
The following example is working for me, filtering out the logs in compile time 
https://github.com/odygrd/quill/tree/external-lib-example/examples

Can you please have a look and see if you are doing something different ? and maybe also try with example. Let me know

**Comment by ZiperRom1** [comment]
Your exemple do work as inteded (I've just compiled and run it), and this is exactly my project structure with a singleton pattern as in your example.

I'm gonna dig my project cmake configuration and let you know, thank you for your example.

**Comment by ZiperRom1** [comment]
Ok I figured it out !

In singleton init you need an actual call to `QuillWrapper::get_logger()->set_log_level(quill::LogLevel::TraceL3);` to set the trace to all the loggers and then the defined macro can lower the log level (but cannot upper it seems).

Make me quite a long to find that because I was focusing on my cmake config...

**Comment by odygrd** [comment]
Thanks for checking on your side! Yes the compile time log level purpose is to exclude log levels from the code. The purpose of it is that is can reduce runtime branches if you do not need that level. It doesn't change (upper) the log level in compile time, sorry for the confusion!

**Comment by ZiperRom1** [comment]
Yes it makes sense now, if the compile log level is `DEBUG` but runtime log level is `INFO` you will not see `DEBUG` logs even if those logs are compiled.
