### ISSUE TITLE
build failure with cmake -DCMAKE_CXX_FLAGS:STRING="-DQUILL_X86ARCH -march=native" under debian11

### ISSUE THREAD

**Issue by qdztxc** [odygrd/quill#255]
main trunk:

make -j16
Scanning dependencies of target quill
[  7%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/backend/TransitEventBuffer.cpp.o
[  7%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/backend/BacktraceStorage.cpp.o
[ 11%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/SignalHandler.cpp.o
[ 18%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/Os.cpp.o
[ 18%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/backend/TimestampFormatter.cpp.o
[ 22%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/FileUtilities.cpp.o
[ 25%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/HandlerCollection.cpp.o
[ 29%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/ThreadContextCollection.cpp.o
[ 33%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/backend/StringFromTime.cpp.o
[ 40%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/LoggerCollection.cpp.o
[ 40%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/backend/BackendWorker.cpp.o
[ 48%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/RdtscClock.cpp.o
[ 48%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/Utilities.cpp.o
[ 55%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/FileHandler.cpp.o
[ 55%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/ConsoleHandler.cpp.o
[ 59%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/Handler.cpp.o
[ 62%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/JsonFileHandler.cpp.o
[ 66%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/RotatingFileHandler.cpp.o
[ 70%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/StreamHandler.cpp.o
[ 74%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/TimeRotatingFileHandler.cpp.o
[ 77%] Building CXX object quill/CMakeFiles/quill.dir/src/LogLevel.cpp.o
[ 81%] Building CXX object quill/CMakeFiles/quill.dir/src/PatternFormatter.cpp.o
[ 85%] Building CXX object quill/CMakeFiles/quill.dir/src/Quill.cpp.o
[ 88%] Building CXX object quill/CMakeFiles/quill.dir/src/Utility.cpp.o
[ 96%] Building CXX object quill/CMakeFiles/quill.dir/src/bundled/fmt/format.cc.o
[ 96%] Building CXX object quill/CMakeFiles/quill.dir/src/bundled/fmt/os.cc.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:151,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/BoundedQueue.h:18,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/UnboundedQueue.h:13,
                 from /home/xinr/quill/quill/include/quill/detail/ThreadContext.h:14,
                 from /home/xinr/quill/quill/include/quill/Logger.h:14,
                 from /home/xinr/quill/quill/include/quill/detail/LogMacros.h:8,
                 from /home/xinr/quill/quill/include/quill/Quill.h:12,
                 from /home/xinr/quill/quill/src/detail/SignalHandler.cpp:8:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h: In member function ‘void quill::detail::BoundedQueueImpl<T>::_flush_cachelines(quill::detail::BoundedQueueImpl<T>::integer_type&, quill::detail::BoundedQueueImpl<T>::integer_type) [with T = unsigned int]’:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h:39:1: error: inlining failed in call to ‘always_inline’ ‘void _mm_clflushopt(void*)’: target specific option mismatch
   39 | _mm_clflushopt (void *__A)
      | ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [quill/CMakeFiles/quill.dir/build.make:225：quill/CMakeFiles/quill.dir/src/detail/SignalHandler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:151,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/BoundedQueue.h:18,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/UnboundedQueue.h:13,
                 from /home/xinr/quill/quill/include/quill/detail/ThreadContext.h:14,
                 from /home/xinr/quill/quill/include/quill/Logger.h:14,
                 from /home/xinr/quill/quill/include/quill/detail/LogMacros.h:8,
                 from /home/xinr/quill/quill/include/quill/Quill.h:12,
                 from /home/xinr/quill/quill/src/Quill.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h: In member function ‘void quill::detail::BoundedQueueImpl<T>::_flush_cachelines(quill::detail::BoundedQueueImpl<T>::integer_type&, quill::detail::BoundedQueueImpl<T>::integer_type) [with T = unsigned int]’:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h:39:1: error: inlining failed in call to ‘always_inline’ ‘void _mm_clflushopt(void*)’: target specific option mismatch
   39 | _mm_clflushopt (void *__A)
      | ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [quill/CMakeFiles/quill.dir/build.make:368：quill/CMakeFiles/quill.dir/src/Quill.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:113：quill/CMakeFiles/quill.dir/all] Error 2
make: *** [Makefile:171：all] Error 2

**Comment by odygrd** [comment]
you will need to add march native to each target in cmake or just add it to cxx flags. Your build doesn't seem like it is using it. 
for example try

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
```

Alternatively you can create a cmake option e.g.
```
option(MARCH_NATIVE "Enabled march native" OFF)`
if (MARCH_NATIVE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
endif()
```

**Comment by odygrd** [comment]
hey is that still an issue on your side or can this be closed ?

**Comment by odygrd** [comment]
closing, please reopen if any issues

**Comment by qdztxc** [comment]
I use “cmake -DCMAKE_CXX_FLAGS:STRING="-DQUILL_X86ARCH -march=native” to generate makefile.
Besides with VERBOSE=1, it shows -march=native is there.

 make -j16 VERBOSE=1
/usr/bin/cmake -S/home/xinr/quill -B/home/xinr/quill/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/xinr/quill/build/CMakeFiles /home/xinr/quill/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: 进入目录“/home/xinr/quill/build”
make  -f quill/CMakeFiles/quill.dir/build.make quill/CMakeFiles/quill.dir/depend
make[2]: 进入目录“/home/xinr/quill/build”
cd /home/xinr/quill/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/xinr/quill /home/xinr/quill/quill /home/xinr/quill/build /home/xinr/quill/build/quill /home/xinr/quill/build/quill/CMakeFiles/quill.dir/DependInfo.cmake --color=
make[2]: 离开目录“/home/xinr/quill/build”
make  -f quill/CMakeFiles/quill.dir/build.make quill/CMakeFiles/quill.dir/build
make[2]: 进入目录“/home/xinr/quill/build”
[  3%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/SignalHandler.cpp.o
cd /home/xinr/quill/build/quill && /usr/bin/c++  -I/home/xinr/quill/quill/include -I/home/xinr/quill/quill -DQUILL_X86ARCH -march=native -O3 -DNDEBUG -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -Wno-unused-private-field -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-parameter -std=gnu++17 -o CMakeFiles/quill.dir/src/detail/SignalHandler.cpp.o -c /home/xinr/quill/quill/src/detail/SignalHandler.cpp
[  7%] Building CXX object quill/CMakeFiles/quill.dir/src/Quill.cpp.o
cd /home/xinr/quill/build/quill && /usr/bin/c++  -I/home/xinr/quill/quill/include -I/home/xinr/quill/quill -DQUILL_X86ARCH -march=native -O3 -DNDEBUG -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -Wno-unused-private-field -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-parameter -std=gnu++17 -o CMakeFiles/quill.dir/src/Quill.cpp.o -c /home/xinr/quill/quill/src/Quill.cpp
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:151,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/BoundedQueue.h:18,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/UnboundedQueue.h:13,
                 from /home/xinr/quill/quill/include/quill/detail/ThreadContext.h:14,
                 from /home/xinr/quill/quill/include/quill/Logger.h:14,
                 from /home/xinr/quill/quill/include/quill/detail/LogMacros.h:8,
                 from /home/xinr/quill/quill/include/quill/Quill.h:12,
                 from /home/xinr/quill/quill/src/detail/SignalHandler.cpp:8:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h: In member function ‘void quill::detail::BoundedQueueImpl<T>::_flush_cachelines(quill::detail::BoundedQueueImpl<T>::integer_type&, quill::detail::BoundedQueueImpl<T>::integer_type) [with T = unsigned int]’:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h:39:1: error: inlining failed in call to ‘always_inline’ ‘void _mm_clflushopt(void*)’: target specific option mismatch
   39 | _mm_clflushopt (void *__A)
      | ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [quill/CMakeFiles/quill.dir/build.make:225：quill/CMakeFiles/quill.dir/src/detail/SignalHandler.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:151,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/BoundedQueue.h:18,
                 from /home/xinr/quill/quill/include/quill/detail/spsc_queue/UnboundedQueue.h:13,
                 from /home/xinr/quill/quill/include/quill/detail/ThreadContext.h:14,
                 from /home/xinr/quill/quill/include/quill/Logger.h:14,
                 from /home/xinr/quill/quill/include/quill/detail/LogMacros.h:8,
                 from /home/xinr/quill/quill/include/quill/Quill.h:12,
                 from /home/xinr/quill/quill/src/Quill.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h: In member function ‘void quill::detail::BoundedQueueImpl<T>::_flush_cachelines(quill::detail::BoundedQueueImpl<T>::integer_type&, quill::detail::BoundedQueueImpl<T>::integer_type) [with T = unsigned int]’:
/usr/lib/gcc/x86_64-linux-gnu/10/include/clflushoptintrin.h:39:1: error: inlining failed in call to ‘always_inline’ ‘void _mm_clflushopt(void*)’: target specific option mismatch
   39 | _mm_clflushopt (void *__A)
      | ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [quill/CMakeFiles/quill.dir/build.make:368：quill/CMakeFiles/quill.dir/src/Quill.cpp.o] 错误 1
make[2]: 离开目录“/home/xinr/quill/build”
make[1]: *** [CMakeFiles/Makefile2:113：quill/CMakeFiles/quill.dir/all] 错误 2
make[1]: 离开目录“/home/xinr/quill/build”
make: *** [Makefile:171：all] 错误 2
