### ISSUE TITLE
backend_thread_sleep_duration support

### ISSUE THREAD

**Issue by qdztxc** [odygrd/quill#256]
From 2.7.0, backend_thread_sleep_duration is replaced by backend_thread_yield.
yield() may not give up cpu. This causes CPU usage of background thread high than sleep wih long duration.

Would you please support both backend_thread_sleep_duration and backend_thread_yield then let user to choose it?

**Comment by sfjhkjdsh** [comment]
I looked at this and realized that in Linux with `SCHED_OTHER` yielding the CPU means a problem with the application design as per man page.

Most common form of scheduling policy is `SCHED_OTHER` and therefore `quill` is not actually yielding the CPU like it advertised. But its not really a problem of quill but standard that yielding is implementation dependent and most of the time its not much useful.

**Comment by odygrd** [comment]
the backend_sleep is back in v2.8.0 for those who want to use it
