### ISSUE TITLE
Export RDTSC clock type

### ISSUE THREAD

**Issue by madhur4127** [odygrd/quill#260]
In my use case, I take timestamps using `chrono::system_clock` and so the log timestamps drift away as it uses RDTSC. This is a problem because the logs the the code should have same clock source.

Currently the default clock is RDTSC, but the clock source is present in the `*/detail` and meddling with it makes me feel at unease as its not part of the public API. Can we export it to public API and also add documentation?

**Comment by odygrd** [comment]
hey, I am not sure I understand exactly what you need to do. Quill supports 3 different clock types 1) rtdsc 2) chrono::system_clock 3) custom clock

You can configure it to use chrono::clock for timestamps in runtime -> https://github.com/odygrd/quill/blob/master/examples/example_trivial_system_clock.cpp#L11

You can also configure it to use your own custom clock (e.g. when simulating time) but you are responsible of updating your custom clock each time -> https://github.com/odygrd/quill/blob/master/examples/example_custom_clock.cpp#L58

**Comment by odygrd** [comment]
do you mean https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/misc/Rdtsc.h or https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/misc/RdtscClock.h ?

Do you also need them under namespace `quill` rather than `quill::detail`.

It is under `detail` because I am not expecting someone to use it directly. Which functions of the api do you need to use ? (just trying to best understand the use case)

**Comment by madhur4127** [comment]
Yeah bare quill (non detail) would be great.

I only need now() just like std chrono

**Comment by madhur4127** [comment]
Maybe clock/rdtsc.h would be better

**Comment by madhur4127** [comment]
Logger will have a clock source for sure, how about adding now() to the logger?

It might be tricky to proceed with the api you mentioned because of interrupts and most users won't take care of it and shoot themselves in the foot

**Comment by odygrd** [comment]
logger tries to be optimal on the hot path, when rdtsc is used there is no clock source. It will simply call `rdtsc()` and pass the value to the logging thread. (https://github.com/odygrd/quill/blob/master/quill/include/quill/Logger.h#L173). Then the logging thread converts those values to wall clock timestamps by synching with `system_clock` as explained above

**Comment by odygrd** [comment]
if you have time try with expose_time_since_epoch branch and see if it solves your issue https://github.com/odygrd/quill/tree/expose_time_since_epoch 

This example will take the `rdtsc()` value in the main thread and will use the Rdtsc clock source of the backend logging thread to convert it to a timestamp

I used it like : 

```c++

#include "quill/Quill.h"
#include <iostream>
#include <stdio.h>
#include <time.h>

int main()
{
  // Start the logging backend thread
  quill::start();

  LOG_INFO(quill::get_logger(), "Hello quill!");

  // Before using quill::time_since_epoch the backend logger thread should at least log once
  quill::flush();

  uint64_t ts_now = quill::time_since_epoch(quill::detail::rdtsc());
  uint64_t ts_secs = ts_now / 1'000'000'000;
  uint64_t ts_ns = static_cast<uint32_t>(ts_now - (ts_secs * 1'000'000'000));

  time_t rawtime = ts_secs;
  struct tm  ts;
  char       buf[80];

  ts = *localtime(&rawtime);
  strftime(buf, sizeof(buf), "%T.", &ts);
  std::cout << buf << ts_ns << std::endl;

  LOG_INFO(quill::get_logger(), "Bye");
}

```

prints on my machine

```
01:34:59.262547453 [24688] example_trivial.cpp:11       LOG_INFO      root         Hello quill!
01:34:59.392675893
01:34:59.392783361 [24688] example_trivial.cpp:28       LOG_INFO      root         Bye
```

**Comment by odygrd** [comment]
i just noticed that you said you are taking `chrono::system_clock` timestamps.. for the above to work you need to switch to taking `rdtsc` timestamps.

If you want to keep taking `chrono::system_clock` timestamps I think the only way to be in perfect sync with the logger would be to also switch the logger to `chrono::system_clock` (https://github.com/odygrd/quill/blob/master/examples/example_trivial_system_clock.cpp#L11)

**Comment by odygrd** [comment]
```c++
#include <chrono>
#include "benchmark/benchmark.h"
#include "quill/Quill.h"

void bm_system_clock(benchmark::State& state)
{
  for (auto _ : state)
  {
    benchmark::DoNotOptimize(std::chrono::system_clock::now().time_since_epoch().count());
  }
}
BENCHMARK(bm_system_clock);

void bm_quill_rdtsc(benchmark::State& state)
{
  quill::start();
  LOG_INFO(quill::get_logger(), "bench");
  quill::flush();

  for (auto _ : state)
  {
    benchmark::DoNotOptimize(quill::time_since_epoch(quill::detail::rdtsc()));
  }
}
BENCHMARK(bm_quill_rdtsc);

// Run the benchmark
BENCHMARK_MAIN();
```

on my machine
```
Run on (16 X 3092.73 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 1024 KiB (x16)
  L3 Unified 25344 KiB (x16)
Load Average: 3.81, 2.58, 2.14
----------------------------------------------------------
Benchmark                Time             CPU   Iterations
----------------------------------------------------------
bm_system_clock       18.5 ns         18.4 ns     37955370
bm_quill_rdtsc        10.1 ns         10.1 ns     69704217
```

**Comment by madhur4127** [comment]
Hey sorry for the delay in the reply, life has been a bit crazy, not the good type of crazy :(

So the concern is that I want to log with lowest latency as possible which means using a simple rdtsc is better because I might have to pay >18ns (in above microbenchmark the caches will be super hot) with system_clock. I think the numbers could be ~90ns with stale caches. So using system_clock will worsen the latency woes

OTOH, I think using your approach for exposing `time_since_epoch` is better.
```
quill::time_since_epoch(quill::detail::rdtsc());
```

As a suggestion on the design, I feel if you design similar to std::chrono clocks because then its easier to use both the clocks generically i.e. with the template and use `Clock::now().time_since_epoch()` and expose a `rdtsc()` member function in the clock.

**Comment by odygrd** [comment]
hey no worries ! I had some time tonight to work on this and pushed some changes. 
Let me know if that seems good to on your side and I can merge it to master.

Example usage:

```c++
#include "quill/Quill.h"
#include "quill/Clock.h"
#include <iostream>

int main()
{
  // use the Clock before the logger started - that is reverting to system clock
  std::cout << "quill_clock:         " << quill::Clock::now().time_since_epoch().count() << "\n";

  // Log at least once for quill:Clock to start using rdtsc
  quill::start();
  LOG_INFO(quill::get_logger(), "Hello quill!");
  quill::flush();

  std::cout << "system_clock         " << std::chrono::system_clock::now().time_since_epoch().count() << "\n";
  std::cout << "quill_clock          " << quill::Clock::now().time_since_epoch().count() << "\n";
  auto const tsc = quill::Clock::rdtsc();
  std::cout << "quill_clock_explicit " << quill::Clock::to_time_point(tsc).time_since_epoch().count() << "\n";
}
```

**Comment by madhur4127** [comment]
This is just the thing I needed. Thank you so much for this.

As a suggestion, I think making TSC value a strong type would result in less API misuse as people won't confuse rdtsc with say nanoseconds.

--

But I've a question, how soon should the user call to_time_point()? As the clock drifts apart can I assume calling this at different points in time will cause result in different time_point? Say I call 1s later and 10min later. Those two time points will be different right?

**Comment by odygrd** [comment]
yeah I was thinking to make rdtsc a strong type but then thought to just keep it simpler without one. 
I will give it a go over the next few days and then merge it.

I would expect most people to use `now()`
`to_time_point(tsc)` is just a convenience to convert an rdtsc value to a timestamp but it shouldn't be needed in most of the cases.

The rdtsc clock is synchronised with the system clock by the logging thread (default value every 500ms). To convert the rdtsc to a timestamp the last synchronised value is used.  So yes if you are using `to_time_point(tsc)` to convert rdtsc values that you took 10 minutes ago you will be losing some accuracy.

for example in a very unlikely scenario

```c++
// let's say current wall time is 01:59:59 
auto x1 = rdtsc();

// sleep for 10 seconds
sleep(10);

// while the thread is sleeping :
// the time is currently 02:00:00, A DST time change for +1 hour occurs, now the wall time is 03:00:00
// Rdtsc clock is synchronised now with the wall clock by the logging thread

// Our thread wakes up
uint64_t ts = to_time_point(x1);

// ts will be something like 2:59:59 (instead of 1:59:59) because we are calculating the time based on the difference 
```
