### ISSUE TITLE
build failure with cmake -DCMAKE_CXX_FLAGS:STRING="-DQUILL_X86ARCH -march=native" under debian11 reopen

### ISSUE THREAD

**Issue by qdztxc** [odygrd/quill#261]
Can't reopen the old one, https://github.com/odygrd/quill/issues/255
open this to track the issue.

**Comment by odygrd** [comment]
check if your cpu supports this command, e.g on linux :

```cat /proc/cpuinfo | grep clflushopt```

`-DQUILL_X86ARCH` only offers some minor cache line optimisation for x86 cpus, even the benchmarks for example are done without it, you should be fine building without it in any case

**Comment by qdztxc** [comment]
Thanks for your quick reply.

My machine doens't support clflushopt. I'll switch to another to use this.
