### ISSUE TITLE
Is it possible to create multiple stdout loggers with different formatters?

### ISSUE THREAD

**Issue by BRevzin** [odygrd/quill#27]
As the question says, I want to create multiple `quill::Logger`s, that all log to `stdout`, but have different formatters. Basically such that:

    LOG_INFO(log_a, "hello"); // [A] hello
    LOG_INFO(log_b, "hello"); // [B] hello

But all to stdout, not to different files. 

The documentation seems to suggest there is a singleton stdout handler with a single formatter. Is it possible to do what I'm suggesting or do I have to manually write the `[A]` and `[B]` for each log line?

**Comment by odygrd** [comment]
Hey, yes that wasn't possible before. 

When using files, I initially I had the problem of calling `fopen` twice on the same file, and having 2 different `FILE*` pointers writing to both of them.
So I only create a file handler only once using its file name as a key. That way the same file never get's opened twice.

For `stdout`, `stderr` that is not the case as the files are already opened by the os.

That should be possible now, please check https://github.com/odygrd/quill/blob/master/examples/example_stdout_multiple_formatters.cpp

You have to provide a unique name to `quill::stdout_handler(...)` for each different format pattern.
