### ISSUE TITLE
Compile issues with latest release on Centos 7

### ISSUE THREAD

**Issue by mbhardwa** [odygrd/quill#273]
/opt/rh/devtoolset-7/root/usr/bin/gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

I have two defines turned on 
-DQUILL_NO_EXCEPTIONS -DQUILL_USE_BOUNDED_QUEUE

Pls see build  errors below
[  3%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/StreamHandler.cpp.o
cd /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/build/quill && /opt/rh/devtoolset-7/root/usr/bin/gcc -DQUILL_NO_EXCEPTIONS -DQUILL_USE_BOUNDED_QUEUE -I/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include -I/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill -O3 -DNDEBUG -fno-exceptions -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -Wno-unused-private-field -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-parameter -std=gnu++1z -MD -MT quill/CMakeFiles/quill.dir/src/handlers/StreamHandler.cpp.o -MF CMakeFiles/quill.dir/src/handlers/StreamHandler.cpp.o.d -o CMakeFiles/quill.dir/src/handlers/StreamHandler.cpp.o -c /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/src/handlers/StreamHandler.cpp
In file included from /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/format.h:48:0,
                 from /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/chrono.h:21,
                 from /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/Fmt.h:20,
                 from /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/handlers/StreamHandler.h:8,
                 from /home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/src/handlers/StreamHandler.cpp:1:
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/core.h: In instantiation of ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = std::experimental::filesystem::v1::path&]’:
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/core.h:1777:29:   required from ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = (fmt::v9::detail::type)15; T = std::experimental::filesystem::v1::path&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/core.h:1901:77:   required from ‘constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {std::experimental::filesystem::v1::path&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {std::experimental::filesystem::v1::path, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/core.h:3206:17:   required from ‘std::string fmt::v9::format(fmt::v9::format_string<T ...>, T&& ...) [with T = {std::experimental::filesystem::v1::path&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::basic_string<char>; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, std::experimental::filesystem::v1::path&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >]’
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/src/handlers/StreamHandler.cpp:34:9:   required from here
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/core.h:3206:44:   in constexpr expansion of ‘fmt::v9::make_format_args<>((* & args#0), (* & args#1))’
/home/mbhardwaj/work/tt.git/Falgo/quill_new/quill/quill/include/quill/bundled/fmt/core.h:1756:3: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
   static_assert(
   ^~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

**Comment by odygrd** [comment]
hey, that static_assert is coming from lib `fmt` It seems that you are trying to pass a user defined type to the logger that doesn't have a formatter. Can you you check https://fmt.dev/latest/api.html#udt and also there is an example here https://quillcpp.readthedocs.io/en/latest/tutorial.html#requirements

**Comment by mbhardwa** [comment]
This is while building quill standalone. I am not including any of my code

Sent from my iPhone

On Mar 21, 2023, at 8:44 PM, Odysseas Georgoudis ***@***.***> wrote:

﻿

hey, that static_assert is coming from lib fmt It seems that you are trying to pass a user defined type to the logger that doesn't have a formatter. Can you you check https://fmt.dev/latest/api.html#udt and also there is an example here https://quillcpp.readthedocs.io/en/latest/tutorial.html#requirements

**Comment by odygrd** [comment]
Thanks i am going to check, are you using master or v2.7.0 tag ?

**Comment by mbhardwa** [comment]
Using Master

Sent from my iPhone

On Mar 22, 2023, at 5:38 AM, Odysseas Georgoudis ***@***.***> wrote:

﻿

Thanks i am going to check, are you using master or v2.7.0 tag ?

**Comment by odygrd** [comment]
should now be fixed on master

**Comment by odygrd** [comment]
Also please note that with the latest merge to master `QUILL_USE_BOUNDED_QUEUE` is a header only variable now. Therefore quill library doesn't have to be recompiled with that flag anymore and it has been removed from cmake. You still need to pass that flag to your `<target>` see https://github.com/odygrd/quill/blob/master/examples/CMakeLists.txt#L72 or https://github.com/odygrd/quill/blob/master/examples/example_bounded_queue_message_dropping.cpp#L3
