### ISSUE TITLE
Recent change breaks logging in nested generic lambdas

### ISSUE THREAD

**Issue by BRevzin** [odygrd/quill#28]
Here's a fairly minimal repo (_both_ lambdas must be generic). On gcc 8.3.0, the following compiles on v1.2.3 but breaks on master (bisect points to c3cd06ce2b2c0708f6e8b852b6cfacf52118b5f0 as the breaking commit)

```cpp
#include <quill/Quill.h>

void f(quill::Logger* log) {
    [log](auto){
        [log](auto){
            LOG_INFO(log, "Hi");
        }(1);
    }(0);
}
```

This is because (for whatever reason), `__FUNCTION__` isn't a constant expression in that context on gcc 8.3 (I think this is [gcc bug 66639](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66639)):

```cpp
void f() {
    [](auto){
        [](auto){
            static constexpr char const* function_name = __FUNCTION__;
            static constexpr int value = function_name[0]; // error on 8.3, ok on 9.2
            (void)value;
        }(1);
    }(0);
}
```

**Comment by odygrd** [comment]
Thanks a lot for reporting and for the investigation.

I was able to reproduce with gcc 8.4 and I have tried many different ways of defaulting `__FUNCTION__` to a default value when it is not usable as a constant expression in gcc < 9, but nothing has worked so far ..

**Comment by odygrd** [comment]
As I don't have another workaround at the moment and I didn't want to completely disable ```__FUNCTION__``` in any gcc version prior to 9.0 could you please use something like the following  in nested lambdas ? 

At least this will make it possible to compile, and also those `*_FN` macros can be enabled only in these special cases.

```c++
#define QUILL_NOFN_MACROS
#include "quill/Quill.h"

int main()
{
  
 LOG_INFO(logger, "Log {}", "hi");

  [default_logger](auto)
  {
    [default_logger](auto)
    {
      LOG_DEBUG_NOFN(logger, "Log {}", "hi");
      LOG_INFO_NOFN(logger, "Log {}", "hi");
      LOG_ERROR_NOFN(logger, "Log {}", "hi");
    }(0);
  }(1);

}
```

**Comment by BRevzin** [comment]
Heh, I basically did the same thing locally (I just have a local fork of quill that passes "(sorry)" as the function name)... since I don't personally want to actually do that ever. Tricky problem for sure.
