### ISSUE TITLE
Lots of colons in RPATH when building the library

### ISSUE THREAD

**Issue by tocic** [odygrd/quill#284]
When building the library via

```shell
cmake -B "build/" -S . -DQUILL_FMT_EXTERNAL=ON -DBUILD_SHARED_LIBS=ON
cmake --build "build/" --verbose
```

my linker is invoked with the following options:

```
-Wl,-rpath,::::::::::::::
```

I managed to get rid of it by removing this line:

https://github.com/odygrd/quill/blob/e42e579f15e8f611b1d8354b29911f64f6d24529/quill/CMakeLists.txt#L114

Do we really need the line? I believe this directory is used for searching the libraries anyway.

Related links:
- https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling
- https://cmake.org/pipermail/cmake/2011-June/044829.html

**Comment by odygrd** [comment]
hey and thanks, I have done that in latest master https://github.com/odygrd/quill/commit/290e360178e1471c4e5dd4c01e3087229f4adb22
