### ISSUE TITLE
Log n bytes of char array

### ISSUE THREAD

**Issue by cadnev** [odygrd/quill#285]
I have an `data[1024]` array of chars containing several null bytes somewhere in the middle, after which there are more non-zero characters. Is there any way to pass to the logger macro the number of bytes that need to be logged?
For example
`LOG_INFO(logger, "char array with null bytes: {}", data, 168);`, where 168 - number of bytes to be logged.

**Comment by cadnev** [comment]
i'l try it. thanks

**Comment by zhuoqiang** [comment]
#351 provides another solution
