### ISSUE TITLE
Report of memory allocation in BoundedQueue

### ISSUE THREAD

**Issue by qiuwei** [odygrd/quill#286]
Does quill report if memory allocation happens in BoundedQueue?
I want to tune the config for a multi-process app based on the stats to reduce the chance of memory allocation in the hot path.

**Comment by odygrd** [comment]
hey, it isn't being reported. It would not worth it reporting it on the hot path as it will add additional overhead.
It would be possible to detect this on the backend worker thread tho if for example we add a callback or a print statement here
https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/spsc_queue/UnboundedQueue.h#L169

**Comment by odygrd** [comment]
Adding it in the above PR.

Running https://github.com/odygrd/quill/blob/master/benchmarks/backend_throughput/quill_backend_throughput.cpp should be enough to trigger allocations. On each new allocation the notificaiton_handler callback is called by the backend worker thread.

By default a message will get logged to `std::cerr`. you can override the behaviour if you want for example :

```c++
  quill::Config cfg;

  cfg.backend_thread_notification_handler = [](std::string const& s) { std::cout << s << std::endl; };

  quill::configure(cfg);
  quill::start();

  ...
```

**Comment by qiuwei** [comment]
Excellent!

**Comment by shuhaowu** [comment]
I randomly encountered this while researching this library. The title of this thread is about "memory allocation in **BoundedQueue**", while the rest of the discussion seems to be about the unbounded queue?

My understanding is that if I use the bounded queue (with message dropping), there should be no memory allocation in the hot path? Is this an incorrect understanding?

**Comment by odygrd** [comment]
hey, that is correct the bounded queue will never perform a memory allocation. It will either drop log messages or block based on flag you decide to define ( https://github.com/odygrd/quill/blob/master/quill/include/quill/TweakMe.h#L105 )

**Comment by shuhaowu** [comment]
Thank you for the very prompt clarification on a Saturday! That makes sense to me based on my review of the BoundedQueue code, but I had to make sure after reading this issue. Thanks again. :bow:
