### ISSUE TITLE
TimeRotatingFileHandler (mode="a") Overwrites The Very First Log When First Rotation Occurs

### ISSUE THREAD

**Issue by teklot** [odygrd/quill#287]
To reproduce:

1. Use the following configuration: quill::time_rotating_file_handler("LogFile.log", "a", quill::FilenameAppend::Date, "M");
2. Log something: LOG_INFO("Greetings!");
3. The LogFile.log contains the message above.
4. Wait for a couple of minutes;
5. Log something else which triggers the rotation: LOG_INFO("Hello there!");
6. The LogFile.log contains the message above but there is no rotated file that contains the first message.
7. The logger works normally from this point in terms of logging and rotation

Note: the behavior is the same with different other parameters when mode="a" is used.

Thanks for looking into this.

**Comment by odygrd** [comment]
hey, thanks for reporting this. Which version are you using is that with the latest master? I will try to reproduce it

**Comment by teklot** [comment]
I am using the latest from vcpkg. Thanks!

**Comment by odygrd** [comment]
thanks for reporting, I have reproduced it and fixed it in the pull request. If you find any more issues please report :)

**Comment by teklot** [comment]
Awesome! Thank you so much!

**Comment by odygrd** [comment]
just did, it is in v2.9.0
