### ISSUE TITLE
cmake add_subdirectory fails

### ISSUE THREAD

**Issue by sstsai** [odygrd/quill#295]
fetched version 2.9.0
cmake add_subdirectory fails with could not find Utility
replacing
`set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/quill/cmake" CACHE STRING "Modules for CMake" FORCE)`
with
`list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/quill/cmake")`
fixes it for me

**Comment by odygrd** [comment]
thanks for reporting this. I have pushed a fix to master
