### ISSUE TITLE
immintrin.h/x86intrin.h adds significantly to compile times

### ISSUE THREAD

**Issue by dirocco** [odygrd/quill#298]
Due to the verbose nature of the AVX512 headers, my build profile is showing an extra 500ms of frontend compile time in Clang for any header that includes quill.

The main offenders are `quill/include/quill/detail/spsc_queue/BoundedQueue.h` and `quill/include/quill/detail/misc/Rdtsc.h` which include `immintrin.h` and `x86intrin.h`. 

Here is a simple patch to fix the issue:

```
diff --git a/quill/include/quill/detail/misc/Rdtsc.h b/quill/include/quill/detail/misc/Rdtsc.h
index d4396b8..28ab967 100644
--- a/quill/include/quill/detail/misc/Rdtsc.h
+++ b/quill/include/quill/detail/misc/Rdtsc.h
@@ -16,7 +16,8 @@
   #if defined(_WIN32)
     #include <intrin.h>
   #else
-    #include <x86intrin.h>
+    #include <x86gprintrin.h>
   #endif
 #endif
 
diff --git a/quill/include/quill/detail/spsc_queue/BoundedQueue.h b/quill/include/quill/detail/spsc_queue/BoundedQueue.h
index 67d2af7..81dc6a6 100644
--- a/quill/include/quill/detail/spsc_queue/BoundedQueue.h
+++ b/quill/include/quill/detail/spsc_queue/BoundedQueue.h
@@ -15,7 +15,7 @@
 
 #if defined(QUILL_X86ARCH)
   #include <emmintrin.h>
-  #include <immintrin.h>
-  #include <x86intrin.h>
 #endif
```

**Comment by odygrd** [comment]
thanks for reporting this and for recommending a solution👍 A fix will be in master soon

**Comment by odygrd** [comment]
it seems this doesn't work in clang 15 and we have to add <immintrin.h>
https://github.com/llvm/llvm-project/blob/f9f92f13f62a95aa425f393c6abb36f90dd5e0f6/clang/lib/Headers/clflushoptintrin.h#L11

**Comment by dirocco** [comment]
Wow that header guard is annoyingly broad, thanks for trying anyways.
