### ISSUE TITLE
Visual Studio project builds but shows errors in fmt/std.h

### ISSUE THREAD

**Issue by teklot** [odygrd/quill#299]
Visual Studio project builds and runs fine but always displays 5 errors below in the Error Window. Thanks for looking into this.

![image](https://github.com/odygrd/quill/assets/520484/55f51d0b-d7e3-446a-8a27-15f0771148d9)

**Comment by odygrd** [comment]
Hey, `quill` depends on a third party format library called `libfmt` (https://github.com/fmtlib/fmt). 

I believe you should report those errors to the above repo as those files are not part of `quill`. To find what version of `libfmt` you are using you need to check which version of `libfmt` is installed in `vcpkg`

**Comment by teklot** [comment]
That's what I figured. Thanks!
