### ISSUE TITLE
Header-only?

### ISSUE THREAD

**Issue by Xottab-DUTY** [odygrd/quill#3]
It would be an awesome feature!

**Comment by odygrd** [comment]
Hello,

There is some code that depends on forward declarations at the moment due to circular dependencies between classes.
 
This will require a bit of refactoring.

I will consider it but not as a top priority, as I would like to support package managers and some other features I am working on.

**Comment by odygrd** [comment]
There are no plans to make quill a single header library at the moment. It will be a lot of effort with no actual benefits and it will also increase compile times. However, I have plans to make it available in the future as a single module file `quill20.mpp` with C++20 and onwards support and no third party dependencies

**Comment by niclar** [comment]
header only is hardly a feature ...learn your tools
