### ISSUE TITLE
BUILD_SHARED_LIBS=ON on Windows does not produce log outputs

### ISSUE THREAD

**Issue by DanielKui** [odygrd/quill#302]
cmake  -DBUILD_SHARED_LIBS=ON -DQUILL_NO_THREAD_NAME_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=./  ..

I use the above command to generate quill.dll & quill.lib to run official demo example_logging_to_file.cpp, no any contents in example_filehandler.log

However, static lib generated by "cmake .. ",  whichi is successfully logging to file.

windows 10 & visual studio 2022

[quill_include.zip](https://github.com/odygrd/quill/files/11632213/quill_include.zip)

Attached my quill included files, I added "QUILL_EXPORT" prefix at the front of necessary functions.

**Comment by DanielKui** [comment]
[dll.zip](https://github.com/odygrd/quill/files/11632301/dll.zip)
This is my fmt quill debug_x64 dll

**Comment by odygrd** [comment]
hey, do you have a previous version that was working ?

**Comment by odygrd** [comment]
I tried to reproduce and when the shared library is used on windows the log file appears empty. 
On linux the shared library is working and output is produced.
Still looking into this

**Comment by odygrd** [comment]
I am not able to figure out why it happens for the shared library on windows.

As a workaround if you call `quill::preallocate()` on each one your the threads before the first log statement, it will work.

If you have any ideas how to fix it let me know, this is only happening with windows dll .. and it seems to be related to static thread_local (https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/ThreadContextCollection.h#L146)

The following example should work with the shared library on windows. 

I used master and I build with 
```-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=ON -DQUILL_BUILD_EXAMPLES:BOOL=ON  -DQUILL_NO_THREAD_NAME_SUPPORT:BOOL=ON```

```c++
#include "quill/Quill.h"
#include <thread>

static char const* filename = "example_filehandler.log";

/**
 * Logging to the same file using multiple loggers
 */

void library_foo_create_logger_and_log()
{
  // Get a handler to the file
  // The first time this function is called a file handler is created for this filename.
  // Calling the function with the same filename will return the existing handler
  std::shared_ptr<quill::Handler> file_handler = quill::file_handler(filename, "w");

  // Create a logger using this handler
  quill::Logger* logger_foo = quill::create_logger("logger_foo", std::move(file_handler));

  LOG_INFO(logger_foo, "Hello from {}", "library foo");
}

void library_bar_create_logger_and_log()
{
  // Because foo already created the handler we will get a pointer to the existing handler
  std::shared_ptr<quill::Handler> file_handler = quill::file_handler(filename, "w");

  // Create a logger using this handler
  quill::Logger* logger_bar = quill::create_logger("logger_bar", std::move(file_handler));

  LOG_INFO(logger_bar, "Hello from {}", "library bar");
}

void library_foo_get_logger_and_log()
{
  // Library foo in a different place wants to obtain the logger and log
  auto logger = quill::get_logger("logger_foo");
  LOG_INFO(logger, "Hello again from library foo");
}

void library_bar_get_logger_and_log()
{
  // Library foo in a different place wants to obtain the logger and log
  auto logger = quill::get_logger("logger_bar");
  LOG_INFO(logger, "Hello again from library bar");
}

int main()
{
  // Start the logging backend thread
  quill::start();

  auto t1 = std::thread(
    []()
    {
      // call pre-allocate first
      quill::preallocate();

      library_foo_create_logger_and_log();
      library_foo_get_logger_and_log();
    });

  auto t2 = std::thread(
    []()
    {
      // call pre-allocate first
      quill::preallocate();

      library_bar_create_logger_and_log();
      library_bar_get_logger_and_log();
    });

  t1.join();
  t2.join();
}
```

**Comment by odygrd** [comment]
It seems that the problem was related to having two same copies of the singleton.. i have put a fix in master 5320c25f8b2cc97eac6dc88948c294f968096745 can you try and let me know if you have any issues ?

There is another issue when quill is used as a shared library. When the main program finishes and the dll is existing it seems that the backend worker thread just vanishes without executing the `_exit()` (https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/backend/BackendWorker.h#L311) functions. As a result you may drop log messages. To avoid dropped messages just call `quill::flush()` at the end of your main.

Can you try with the fix from master and let me know if it works good for you ?

**Comment by odygrd** [comment]
I have fixed the dropping messages on application exit when dll is used. 
The examples seem to be working now, Also I ran the whole test suite with `quill.dll` on windows and it seems good. 

Please use 5178dd52266e657a920178fb2607c8afa106a758 or `v2.9.2`

To compile on windows use CMake flags

```-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=ON```

**Comment by DanielKui** [comment]
WIN32
_WINDOWS
NDEBUG
_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
CMAKE_INTDIR="Release"
quill_EXPORTS
QUILL_DLL_EXPORT

The above was my definition in my visual studio.


![image](https://github.com/odygrd/quill/assets/578118/6fc38ce2-536b-45c0-88dc-7b15896fe9ab)

I also used "-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=ON". 
 example_filehandler.log still does not produce any logs.
Somehow, x64 debug version, does not even generate  example_filehandler.log . x64 release can generate  example_filehandler.log , but no contents.
[demo_x64.zip](https://github.com/odygrd/quill/files/11648142/demo_x64.zip)

**Comment by DanielKui** [comment]
Thanks a lot, it works for me

**Comment by odygrd** [comment]
hey, glad it is working now. This flag is defined as part of CMake (https://github.com/odygrd/quill/blob/master/quill/CMakeLists.txt#L123) but when building outside of it, it has to be provided
