### ISSUE TITLE
will it create a single thread to handle io?

### ISSUE THREAD

**Issue by bethebest0622** [odygrd/quill#311]
great job, i was using printf and write as my log function.

could you explain the difference and advantage?

in my understanding, the best practice is to open a single thread, the main only send request, the single thread handle the real io things.

is it what quill implement? and in that case, when i use quill, the cpu will need one more processor to monitor the io request.

is this correct?

thanks a lot

**Comment by odygrd** [comment]
The library will just pass a copy of the type you want to log to a backend thread. The backend thread will handle formatting the type to string and writing it to a file outside the hot path. 

You don’t need an additional hardware core as those are software threads. However if you only have a single processor core then it will have to handle your hot path and the backend thread work, so ideally you use an isolated core for hot path and you pin the backend thread to a different core

**Comment by odygrd** [comment]
Closing for now, feel free to reopen for any other questions / issues
