### ISSUE TITLE
Record/log binary data

### ISSUE THREAD

**Issue by alphanso** [odygrd/quill#312]
Hi,

I want to record binary data using quill. Is that possible? I want to use zstd compression to compress that binary data

**Comment by odygrd** [comment]
Hey, do you mean that you want to record eg messages coming from the network to a file in binary format?

Or do you mean that you want to produce binary log files for all your application log statements?

**Comment by alphanso** [comment]
Actually, both of them. I have lot of logs and it will save me space if I can log data as binary or compressed. I will prefer zstandard compression. 
Also, I need to record binary data coming over network for further analysis. I am writing my own recorder for this

**Comment by odygrd** [comment]
This library doesn't do binary logs. On the hot path, we log objects as binary to an SPSC queue, but then the backend thread decodes them into human-readable files. You can log any user-defined type without worrying about serializing each type to plain old data. So, sorry, no binary logging support here!

For binary logging you might have to look at other libraries for example https://github.com/morganstanley/binlog

**Comment by alphanso** [comment]
I am suggesting that give user an option that backend thread skips decoding and directly log it to a file.
