### ISSUE TITLE
Meson Build Scripts

### ISSUE THREAD

**Issue by yahmed153** [odygrd/quill#317]
Is it possible to add a meson build script to your repo. Thanks for your time

**Comment by odygrd** [comment]
Hey,
I'm not very familiar with the Meson build system to create the scripts. It'd be really nice to have some Meson / Bazel build scripts for the project. If anyone's interested, feel free to send in those pull requests. Your contributions are most welcome!

**Comment by odygrd** [comment]
Meson support is now available for the latest version and onwards. Please see https://github.com/odygrd/quill?tab=readme-ov-file#meson
