### ISSUE TITLE
Static quill library can not be linked into shared library because of missing fpic

### ISSUE THREAD

**Issue by TillAlex** [odygrd/quill#319]
When installing quill using make install the installed shared library can not be linked into shared libraries, because it's not compiled using -fPIC. I am not sure what is the best practice here: Always compile static libraries using -fPIC? Add an option for -fPIC? Let the user handle it?

**Comment by odygrd** [comment]
hey, thanks for reporting this. I have fixed this in 00d25c7aee7112333348d88067ea92e9d896f185
For static library `fPIC` is enabled by default with an option for the user to disable it. Can you check if that is now working for you ?

**Comment by TillAlex** [comment]
Your commit solves the issue. Thanks for the prompt fix! And thanks for your great work!
