### ISSUE TITLE
Support {fmt} Version 7

### ISSUE THREAD

**Issue by jwillikers** [odygrd/quill#32]
Quill needs updated to support [{fmt} 7](https://github.com/fmtlib/fmt/releases/tag/7.0.0).

When using a an external {fmt} of version 7 or higher, compilation fails.
```
_deps/quill-src/quill/include/quill/detail/LogMacros.h:37:8: fatal error: no member named 'internal' in namespace 'fmt'
  fmt::internal::check_format_string<std::remove_reference_t<Args>...>(format_str);
  ~~~~~^
```

The `internal` namespace was renamed to `detail` in {fmt} version 7.
Updating the namespace used in LogMacros.h fixes the issue, as shown below.
```cpp
/**
 * Check in compile time the correctness of a format string
 */
template <typename S, typename... Args, typename Char = fmt::char_t<S>>
constexpr void check_format(const S& format_str, Args&&...)
{
  fmt::detail::check_format_string<std::remove_reference_t<Args>...>(format_str);
}
```

**Comment by odygrd** [comment]
Hey, thanks for reporting!
This is now fixed in master and also bundled `libfmt` is updated to `7.0.2`
For package managers the quill version needs to be updated to '1.3.3' to support this. I am planning to update them within the next few days

**Comment by jwillikers** [comment]
No problem. I wish I'd had time to PR. Quill has been very useful, thanks as always!

**Comment by odygrd** [comment]
thank you :)
