### ISSUE TITLE
Try to reduce quill build time

### ISSUE THREAD

**Issue by azuresigma** [odygrd/quill#338]
We tried to build our application with/without quill. The build time is reduced from 2 minutes 32 seconds to 30 seconds when quill is removed from the include(we replace quill macro with no op and everything else being the same). 
It will be nice if quill build time can be reduced. In our analysis, it is mostly due to a lot of template instantiations.

**Comment by azuresigma** [comment]
environment: gcc 12, linux.

**Comment by odygrd** [comment]
Hey, yes the library does the compile time checks for each statement, and also it has to generate a function to deserialise. 

There are quite a few template instantiations for each log statement and many other things are templated to avoid runtime costs. 

I haven't looked into the build time performance yet but it's something that I'm planning to do at some point in the future.

Can you double check the numbers in your original message please ? From 2.5 minutes to 30 minutes doesn't sound right.

**Comment by azuresigma** [comment]
sorry, it was a typo. I meant to say '30 seconds'. corrected in original post. thanks.

**Comment by jf-0** [comment]
Hey, I just wanted to comment here, because I kinda have the same "issue".
With quill my project takes around 8.5 min. to compile and without it's done in 1 min. on msvc 2022.

It's a cool library, and thanks for all of your work, but it really increases the build times ;)

**Comment by diehard2** [comment]
I ran into the same issue. If found if you make a precompiled header file and add in quill, it greatly accelerates even a clean build. Note that there are diminishing returns on the clean build approach if you start adding in other things

**Comment by odygrd** [comment]
Compile times have been greatly improved in `v4.0.0`. If you get a change consider trying out the new version. Closing for now
