### ISSUE TITLE
inline get_root_logger()

### ISSUE THREAD

**Issue by zhuoqiang** [odygrd/quill#348]
currently the `get_root_logger()` is defined in `Quill.cpp`. 

I wonder if it could be moved to header file as an inline function to save the extra function call indirection

**Comment by zhuoqiang** [comment]
another issue is that there is an assert inside `get_root_logger()`, so client code could not check root logger using `get_root_logger()`.

how about we add a inlined unchecked version `get_root_logger()`, something like:

```cpp

inline auto get_root_logger_unchecked() noexcept {
    return _g_root_logger;
}

**Comment by odygrd** [comment]
I don't mind adding an unchecked version. 
probably we can move it to the header if we use `extern` https://github.com/odygrd/quill/blob/9a270d5d6f57a3ac19451292e3a9f370fcd744b1/quill/src/Quill.cpp#L17C9-L17C24
