### ISSUE TITLE
log char array as c style null-terminated string

### ISSUE THREAD

**Issue by zhuoqiang** [odygrd/quill#351]
tto log char array as c style null-terminated string, there maybe 2 issue:

- the char array may be decayed to `char*` and passed to logging thread, which may become dangling pointer later when the actual logging takes place (a char array on stack for example)
- there maybe `\0` in the middle of the array, to output it like a normal c style string (stop at the first `\0`), the length has to be calculated

not sure if the array is copied to logging thread or only the decayed pointer been copied in current quill lib?

I have used the following for safety anyway.

```cpp
// a dedicated type for wrapping char array
// it is copyable by value to background logging thread
// 
// do not use std::array directly since it will be formatted like a container in fmt
template <size_t N>
struct CharArrayAsStringWrapper {
    std::array<char, N> data;
};

// helper method for end user
template <size_t N>
constexpr auto AsString(const char (&a)[N]) noexcept {
    return CharArrayAsStringWrapper<N>{.data = std::to_array(a)};
}

namespace fmt {

// special formatter for our char array wrapper
template <size_t N>
struct formatter<CharArrayAsStringWrapper<N>> : formatter<string_view> {
    auto format(const CharArrayAsStringWrapper<N>& d,
                format_context& ctx) const -> format_context::iterator {
        // treated it like a normal null-terminated c string
        const auto length = ::strnlen(d.data.data(), d.data.size());
        return format_to(ctx.out(), "{}", string_view(d.data.data(), length));
    }
};
} // namespace fmt

// usage

char a[32] = "hello";

fmt::print("this is a greeting: {}", AsString(a));

LOG_INFO("this is a greeting: {}", AsString(a));
```

not sure if something similar could be added to quill lib

**Comment by usefulcat** [comment]
I was curious so I tried logging a c style string via a const char* and stepped through the code in a debugger. At line 230 of Serialize.h I see it using memcpy to copy the contents of the string (not just the pointer), so I don't think there's a dangling pointer problem.

**Comment by zhuoqiang** [comment]
> I was curious so I tried logging a c style string via a const char* and stepped through the code in a debugger. At line 230 of Serialize.h I see it using memcpy to copy the contents of the string (not just the pointer), so I don't think there's a dangling pointer problem.

thanks for the quick verification.

further question: is there decay when logging char array? 

I mean, if I pass `char a[3] = {'a', 'b', 'c'}`, will the fmtlib see a `char[3]` or a `char p*` (point to the quill internal buffer of cause)?

I see `strlen` is used in `Serialize.h`, not sure if it is an issue for handing char array without `\0`

**Comment by usefulcat** [comment]
I don't know offhand, I suggest you try it and see what happens. Make a small test program and step through it in a debugger.

**Comment by odygrd** [comment]
Thanks the PR is merged, closing this
