### ISSUE TITLE
Synchronous mode for debugging 

### ISSUE THREAD

**Issue by qiuwei** [odygrd/quill#359]
First of all, thanks a lot for this great library.
I am using quill in production happily.

However, during the development phase, assert failures make the logging message incomplete(at least, not until the assert failure occurs).
I fully understand this is expected due to the fact that the quill backend runs in a separate thread asynchronously, but is there any workaround(ideally a config option) so that the log message can be made complete during development?

**Comment by qiuwei** [comment]
Cool, thanks a lot for the tip!

**Comment by odygrd** [comment]
Another option is to start quill with the provided singal handler. It will catch the SIGABRT and flush the log

https://github.com/odygrd/quill/blob/d30a528ec422d172c3e9065fdfae83433243a95c/quill/include/quill/Quill.h#L84

**Comment by qiuwei** [comment]
@odygrd Thanks for the advice. May I know what is the consequence of enabling with_signal_handler? Why is it disabled by default?

**Comment by odygrd** [comment]
Applications usually tend to write their own as they may have custom logic to handle each signal. 
It’s not really a part if a logging library but some users may not want to write their own.
The provided one will flush the log when your application crashes or when for example you stop with ctrl-c

**Comment by qiuwei** [comment]
Thanks for the detailed explanation. Since I already have a signal handler for the application, I guess it is best to call `quill::flush()` there.
