### ISSUE TITLE
to support compiling dynamic library

### ISSUE THREAD

**Issue by sandodo** [odygrd/quill#38]
Hi Quill team,

We are currently using your quill logger for our C++ projects which works brilliantly.  Thanks.

Now we would like to utilize quill logger for JAVA applications as well by loading it as a dynamic library. In this way, Quill need to dynamically depend on fmt lib as well instead of being bundled together, as we are also using fmt-cpp's dynamic library.

Is that possible you can help to add the support of generating dynamic library as well, together with existing support of static library for quill?

Thanks in advance,
Xiong

**Comment by odygrd** [comment]
Hello thanks for using the logger. 
1) Which OS are you using ?
2) Are you building quill from scratch or have you installed it via a package manager?

If you are building it from scratch, It is possible to build quill using an external fmt version by passing ‘-DQUILL_FMT_EXTERNAL=ON’ as cmake argument and that would use your shared lib fmt instead of the bundled one. From there you can use ‘DBUILD_SHARED_LIBS=ON’ to build quill as shared library. 

So the combination of those two flags should give you what you need. Let me know if you are having any issues with this or if it doesn’t work and any changes in the code are required.

**Comment by sandodo** [comment]
Thanks @odygrd 

It is a linux box with CentOS Linux release 7.4.1708
And I am building quill from source codes with version 1.4.0

Below is my commands, and it will build libquill.a instead of libquill.so even if I provided -DBUILD_SHARED_LIBS=ON.

linux:~/3rd_party/quill-1.4.0/cmake_build$ cmake3 -DCMAKE_PREFIX_PATH=/home/3rd_party/fmt-6.2.0/lib64/cmake/fmt -DQUILL_FMT_EXTERNAL=ON -DCMAKE_INSTALL_PREFIX=/home/3rd_party/quill-1.4.0 -DBUILD_SHARED_LIBS=ON ..
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /home/gcc/gcc-9.2.0/bin/gcc
-- Check for working C compiler: /home/gcc/gcc-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/gcc/gcc-9.2.0/bin/g++
-- Check for working CXX compiler: /home/gcc/gcc-9.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Build Type: Release
-- Quill Version: 1.4.0
-- QUILL_NO_EXCEPTIONS: OFF
-- QUILL_USE_BOUNDED_QUEUE: OFF
-- QUILL_FMT_EXTERNAL: ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/3rd_party/quill-1.4.0/cmake_build
linux:~/3rd_party/quill-1.4.0/cmake_build$ make install
Scanning dependencies of target quill
[  4%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/Utilities.cpp.o
[  8%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/Os.cpp.o
[ 12%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/RdtscClock.cpp.o
[ 16%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/RecursiveSpinlock.cpp.o
[ 20%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/Spinlock.cpp.o
[ 25%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/FileUtilities.cpp.o
[ 29%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/BackendWorker.cpp.o
[ 33%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/BacktraceLogRecordStorage.cpp.o
[ 37%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/Config.cpp.o
[ 41%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/HandlerCollection.cpp.o
[ 45%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/LoggerCollection.cpp.o
[ 50%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/LogManagerSingleton.cpp.o
[ 54%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/ThreadContextCollection.cpp.o
[ 58%] Building CXX object quill/CMakeFiles/quill.dir/src/detail/TimestampFormatter.cpp.o
[ 62%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/ConsoleHandler.cpp.o
[ 66%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/FileHandler.cpp.o
[ 70%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/RotatingFileHandler.cpp.o
[ 75%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/StreamHandler.cpp.o
[ 79%] Building CXX object quill/CMakeFiles/quill.dir/src/handlers/TimeRotatingFileHandler.cpp.o
[ 83%] Building CXX object quill/CMakeFiles/quill.dir/src/LogLevel.cpp.o
[ 87%] Building CXX object quill/CMakeFiles/quill.dir/src/PatternFormatter.cpp.o
[ 91%] Building CXX object quill/CMakeFiles/quill.dir/src/Quill.cpp.o
[ 95%] Building CXX object quill/CMakeFiles/quill.dir/src/Utility.cpp.o
[100%] Linking CXX static library libquill.a
[100%] Built target quill
Install the project...
-- Install configuration: "Release"
-- Installing: /home/3rd_party/quill-1.4.0/lib64/cmake/quill/quill-config.cmake
-- Installing: /home/3rd_party/quill-1.4.0/lib64/cmake/quill/quill-config-version.cmake
-- Installing: /home/3rd_party/quill-1.4.0/lib64/libquill.a
-- Installing: /home/3rd_party/quill-1.4.0/lib64/cmake/quill/quill-targets.cmake
-- Installing: /home/3rd_party/quill-1.4.0/lib64/cmake/quill/quill-targets-release.cmake
-- Installing: /home/3rd_party/quill-1.4.0/include/quill
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/Fmt.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/LogLevel.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/Logger.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/PatternFormatter.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/Quill.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/QuillError.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/TweakMe.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/Utility.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/Version.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/bundled
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/bundled/invoke
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/bundled/invoke/invoke.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/BackendWorker.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/BacktraceLogRecordStorage.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/BoundedSPSCQueue.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/Config.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/HandlerCollection.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/LogMacros.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/LogManager.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/LogManagerSingleton.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/LoggerCollection.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/LoggerDetails.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/ThreadContext.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/ThreadContextCollection.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/TimestampFormatter.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/UnboundedSPSCQueue.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/events
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/events/BacktraceEvent.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/events/BaseEvent.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/events/FlushEvent.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/events/LogRecordEvent.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/events/LogRecordMetadata.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/AlignedAllocator.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Attributes.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Common.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/FileUtilities.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Macros.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Os.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Rdtsc.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/RdtscClock.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/RecursiveSpinlock.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Spinlock.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/TypeTraits.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/TypeTraitsCopyable.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/detail/misc/Utilities.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers/ConsoleHandler.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers/FileHandler.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers/Handler.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers/RotatingFileHandler.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers/StreamHandler.h
-- Installing: /home/3rd_party/quill-1.4.0/include/quill/handlers/TimeRotatingFileHandler.h
-- Installing: /home/3rd_party/quill-1.4.0/pkgconfig/quill.pc


Thanks,
Xiong

**Comment by odygrd** [comment]
Thanks for sending me the commands. Can you try with the latest commit from master 57baae85524289316900e354fb95e6f0b89895fd and let me know ? `-DBUILD_SHARED_LIBS=ON` should now work.

**Comment by sandodo** [comment]
Sure, will do asap and let you know. Before that, a quick question, may I know if I can directly take the latest CMakeList.txt file and replace it into my existing release 1.2.0 or 1.4.0 to have the support of -DBUILD_SHARED_LIBS=ON? Thanks

**Comment by odygrd** [comment]
Yes you just need the change in cmake to remove ‘STATIC’ from ‘add_library()’ for it to build as shared library

**Comment by sandodo** [comment]
Thanks a lot for your help, in the latest code from master branch, cmake file works correctly with -DBUILD_SHARED_LIBS=ON.

And it also works correctly after I made following changes for v1.2.0 in quill/quill/CMakeLists.txt
> # Add as a library
> add_library(${TARGET_NAME} STATIC "")

< # Add as a library
< add_library(${TARGET_NAME} "")

and same for v1.4.0 in quill/CMakeLists.txt
> # Add as a library
> add_library(${TARGET_NAME} STATIC "")

< # Add as a library
< add_library(${TARGET_NAME} "")

Cheers,
Xiong

**Comment by odygrd** [comment]
Thanks for reporting, I am planing to set the `RPATH` in cmake and submit a fix within the next few days, if it is urgent for now please setup the `LD_LIBRARY_PATH`.

**Comment by sandodo** [comment]
sure, thanks a lot

**Comment by odygrd** [comment]
I think if you add the following before ‘add_library’ it should work but I didn’t have a chance to test it. If you would like to try let me know

‘’’ 
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE) 
‘’’

**Comment by odygrd** [comment]
Hey, can you please try again with the latest cmake from master 362f4d5e476d4f4a0c8634f0f9a54094685cf83d and confirm all is okay for you.

I tested it on ubuntu and it looks good

```
ody@ody-Parallels-Virtual-Platform:~/CLionProjects/quill/cmake-build-shared$ ldd -d ~/ody_install/quill/lib/libquill.so.1.4.1 
	linux-vdso.so.1 (0x00007ffd1c6f8000)
	libfmt.so.7 => /home/ody/ody_install/fmt/lib/libfmt.so.7 (0x00007ff2ce4c5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff2ce490000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff2ce2af000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff2ce294000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff2ce0a2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff2ce51b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff2cdf53000)
```

**Comment by qwertynat** [comment]
just tested, that works on fedora32 now.

**Comment by sandodo** [comment]
Sorry for reply late. Was busy yesterday.

I have tested the latest code in master branch, the generation of so file as well as linking to libfmt.so.6 works correctly.

And I have also tested quill version 1.2.0 and 1.4.0, applying following lines to CMakeLists.txt works correctly as well for so file and linking to libfmt.so.6 

```
> # Add as a library
> add_library(${TARGET_NAME} STATIC "")

< # Add as a library
< set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
< set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
< add_library(${TARGET_NAME} "")
```

Cheers,
Xiong

**Comment by odygrd** [comment]
Thanks for taking the time to test this also. I think it is fine as it is now in master with the RPATH being set during make install.

Closing this, let me know if anything else comes up!
