### ISSUE TITLE
Quill for .NET with C++/CLI project

### ISSUE THREAD

**Issue by batuhancengiz** [odygrd/quill#386]
Hello,

Have you ever tried to use your library on .NET side? We have two applications and one is written by c++ and other is by c# so for c++ we have decided to use your lib for logging and to be sync we also want to use on c# side. But I got unmanaged/managed code error while implementing to c# side. Do you have any idea how to fix?

![image](https://github.com/odygrd/quill/assets/82826094/7d0892bc-f0b4-4c88-96e8-310dfc4ff2e3)

![image](https://github.com/odygrd/quill/assets/82826094/c06de8ab-e9cd-404d-b578-a1f9c6c5ade1)

**Comment by odygrd** [comment]
hey, I have not tried to run the library on .NET. Can you maybe tried the answers from https://stackoverflow.com/questions/18037232/c-cli-correct-way-to-use-pragma-managed-unmanaged ?
