### ISSUE TITLE
Error, use cmake -DCMAKE_PREFIX_PATH=xxx

### ISSUE THREAD

**Issue by chinahuangyong** [odygrd/quill#393]
![DeepinScreenshot_select-area_20240118135023](https://github.com/odygrd/quill/assets/20627061/b483c2d2-2d1b-4862-8ded-8d30850aac4c)

**Comment by AlemSnyder** [comment]
What was the command you ran?

I'm going to go out on a lib here and say that `/usr/local/pkgconfig` is protected by elevated privileges.

**Comment by chinahuangyong** [comment]
command is `cmake -DCMAKE_PREFIX_PATH=/home/huangyong/quill_build ..`

**Comment by odygrd** [comment]
i am not able to reproduce this, `DCMAKE_PREFIX_PATH` specifies installation prefixes to be searched by the `find_package()`
It looks like you ran `cmake -DCMAKE_PREFIX_PATH=/home/huangyong/quill_build ..` on your own project  and you want to find quill installed under /home/huangyong/quill_build correct ?
