### ISSUE TITLE
Adding Conda Package

### ISSUE THREAD

**Issue by jamespinkerton** [odygrd/quill#394]
Hi! I'm using quill and it's working great. Would it be possible to create a conda package to release quill as well?

Thanks so much,
James

**Comment by odygrd** [comment]
Sorry for the delay. I have made an attempt and a PR to conda-forge for the latest version. I will let you know when it is merged

**Comment by odygrd** [comment]
Package is now available for the latest version 

https://anaconda.org/conda-forge/quill

**Comment by jamespinkerton** [comment]
I tried installing the package. I can't find the libquill.a? Did that get installed?

**Comment by odygrd** [comment]
the latest major version (`v4`) is header only, there won't be a `libquil.a`

You can wrap it to a static library if you wish, please see 
https://github.com/odygrd/quill/tree/master/examples/recommended_usage

Currently only `v4` is available as conda package. `v4` and `v3` are not compatible

**Comment by jamespinkerton** [comment]
I got everything working with v4 and the library. Thanks for the help it's working great!
