### ISSUE TITLE
Please add prefix QUILL_ to log macros like LOG_INFO

### ISSUE THREAD

**Issue by azuresigma** [odygrd/quill#40]
This is causing macro conflicts for me, as 1 of the libraries I use has the same log macro. It will be better to always have a prefix for macros like LOG_INFO, which is too easy to have a naming conflict without prefix. 

Thanks a lot.

**Comment by odygrd** [comment]
hey, I don't mind doing this but since it will be a breaking change, I will provide this as an option for example you will have to `#define QUILL_USE_PREFIXED_MACROS`

**Comment by azuresigma** [comment]
That works. Thanks a lot.

**Comment by odygrd** [comment]
I added an option in 89d0986270425975f52bf242fd889d7ec17bed06.

Can you try something like this:

```
#define QUILL_DISABLE_NON_PREFIXED_MACROS
#include "quill/Quill.h"
```

Closing for now, please let me know if you have any more issues
