### ISSUE TITLE
Add JSON-structured console logging

### ISSUE THREAD

**Issue by Exctues** [odygrd/quill#413]
Currently I see that JSON structured logging is implemented for files (which is amazing), but not for console (stdout)

I think it would be amazing  to be able to to choose between logging structured-json in either file or stdout out of the box!

Thanks for consideration!

**Comment by cchapman-kxs** [comment]
+1

**Comment by odygrd** [comment]
added in 404d78c7d5945dac070a0b04f7dc5cf5247ec4dd
