### ISSUE TITLE
__rdtscp vs __rdtsc in logger_benchmarks

### ISSUE THREAD

**Issue by DanielekW** [odygrd/quill#420]
I have a question to logger_benchmarks. In ns_per_rdtsc_tick() to convert rdtsc to wall time __rdtsc() is used while next in benchmark tests  __rdtscp(&aux) is used. Why in ns_per_rdtsc_tick() you do not use __rdtscp?

**Comment by odygrd** [comment]
`__rdtsc()` should have lower overhead.
`__rdtscp()` has an additional serialising barrier, I believe I used it in benchmarks for more accurate results.
