### ISSUE TITLE
Legacy PatternFormatter attributes

### ISSUE THREAD

**Issue by llchan** [odygrd/quill#429]
I see that the `PatternFormatter` attributes were changed in a backwards-incompatible way, and furthermore it is not evident until runtime.  It would be better to keep the legacy attributes around as aliases for now, given that we did not do a major version bump.

I would suggest something like a `QUILL_DISABLE_LEGACY_PATTERN_FORMATTER_ATTRIBUTES` that allows users to test against the new set of attributes in an opt-in way, and when 4.0.0 lands they can be fully removed.

**Comment by odygrd** [comment]
I used keep the major version for bigger changes. In the past, numerous minor version increments broke backward compatibility without complaints.

Regarding the consideration of adding a preprocessor flag for this purpose, I don't believe it's worth the complexity and the effort. However, pull requests are welcome.

Moving forward any future incompatible API changes will result in a major version update.
