### ISSUE TITLE
timestamp point

### ISSUE THREAD

**Issue by qwertynat** [odygrd/quill#43]
Hi,

At what  point does Quill calculate the timestamp? is it at the time the caller sends to the log thread? or when the worker thread eventually gets it from the work queue?

**Comment by odygrd** [comment]
Hello, the timestamp is the time the caller thread sends a log to the log thread. 

The caller via the `LOG_` creates a `LogRecordEvent' which inherits from `BaseEvent`. The timestamp is set when the `BaseEvent` is created by the caller here : https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/events/BaseEvent.h#L93

The backend worker thread processes the `BaseEvents` and logs the timestamps from all caller threads in order. That means if you have multiple threads logging you will see the log in the same timed order as the threads send the log to the backend thread.

**Comment by odygrd** [comment]
Closing this, if you have any more questions please let me know
