### ISSUE TITLE
Multiple definitions of `quill::detail::on_alarm(int)` in `quill/backend/SignalHandler.h`

### ISSUE THREAD

**Issue by ZijunH** [odygrd/quill#457]
When including quill in different compilation units, gcc gives the error `include/quill/backend/SignalHandler.h:336: multiple definition of 'quill::detail::on_alarm(int)'`. Adding inline to the function name fixes the issue.

**Comment by odygrd** [comment]
thank you for reporting. Fixed in 02119a418c2fa5ed18311f3e2b9ad3f615926a0a
