### ISSUE TITLE
"Version Info" Constants in global namespace 

### ISSUE THREAD

**Issue by 12AT7** [odygrd/quill#465]
I am mostly done migrating my code to the new version 4.  Looks great!

I am not sure these should be in the global namespace, in `Backend.h`, as opposed to `quill`:
```
/** Version Info **/
constexpr uint32_t VersionMajor{4};
constexpr uint32_t VersionMinor{4};
constexpr uint32_t VersionPatch{0};
constexpr uint32_t Version{VersionMajor * 10000 + VersionMinor * 100 + VersionPatc
h};
```
These are useful (I dump them to my boot spew) but we are asking for a namespace collision with other libraries and it is also not clear when reading just `VersionMajor` what it refers to.   If it was `quill::VersionMajor` then everything would be crystal clear.

**Comment by odygrd** [comment]
Thanks for reporting :) Yes they should be under the namespace, I will get that fixed
