### ISSUE TITLE
Build failure on Windows arm64

### ISSUE THREAD

**Issue by star-hengxing** [odygrd/quill#485]
https://github.com/xmake-io/xmake-repo/actions/runs/9736499244/job/26867239415?pr=4529

https://github.com/odygrd/quill/blob/26fabc42a0c21675f87c5ddc0f6cc4cd82e7791a/quill/include/quill/core/Rdtsc.h#L48

Work with:

```c
#elif (defined(__ARM_ARCH) && !defined(_MSC_VER))
```

**Comment by odygrd** [comment]
thanks for reporting 👍 Adding this fix to the next release
