### ISSUE TITLE
[feature request] bind log level to handlers

### ISSUE THREAD

**Issue by zhangzq** [odygrd/quill#49]
Hi, I use a single log with two handlers, one is file handle, the other is stdout. 

I need to log all to file (set_log_level=TraceL3) but only log error (and critical) on stdout(set_log_level=Error).

However, currently, log levels are binded to log instance but not handlers. It will be great if log levels are binded to handlers (just like formatter, and also in Python).

**Comment by odygrd** [comment]
Hey, yes the log levels are not currently related to handlers. 
Do you mean something like this [Filters](https://docs.python.org/2/library/logging.html#filter-objects) ?

In this case you could have one `logger` logging to both a `file` and `stdout` handler. Then you could have set different filters per handler to not log certain log messages. 

Would something like this work for you ?

**Comment by zhangzq** [comment]
Fitlter will works but be too complicated. Setting level for handlers needs only a small code work, I think.

> Handler.setLevel(level)
>
> Sets the threshold for this handler to level. Logging messages which are less severe than level will be ignored. When a handler is created, the level is set to NOTSET (which causes all messages to be processed).

from https://docs.python.org/2/library/logging.html#handler-objects.

**Comment by odygrd** [comment]
Hello, I have added filters to master since that would give more flexibility to the user rather than setting the log level.
Please look at https://github.com/odygrd/quill/blob/master/examples/example_filters.cpp it should do what you would like to do.

Let me know if you have any issues.

**Comment by zhangzq** [comment]
> Hello, I have added filters to `master` [27f582d](https://github.com/odygrd/quill/commit/27f582d9302d2a973faa10d8efa37bdca6b59a41) since that would give more flexibility to the user rather than just setting the log level.
> Please look at https://github.com/odygrd/quill/blob/master/examples/example_filters.cpp it should do what you would like to do.
> 
> Let me know if you have any issues.

Filters are too heavily for this. Will you add  `set_log_level` for handlers directly?

**Comment by zhangzq** [comment]
> Hello, I have added filters to `master` [27f582d](https://github.com/odygrd/quill/commit/27f582d9302d2a973faa10d8efa37bdca6b59a41) since that would give more flexibility to the user rather than just setting the log level.
> Please look at https://github.com/odygrd/quill/blob/master/examples/example_filters.cpp it should do what you would like to do.
> 
> Let me know if you have any issues.

Hi, I need to change log level on runtime for filter. It seems that I couldn't get filters or handlers on runtime.

**Comment by odygrd** [comment]
Hello,

Please try with ad15aa20d3e71c550690d305774db307e80eaf74 from master and let me know if you have any issues.

Also see [example](https://github.com/odygrd/quill/blob/master/examples/example_handler_log_levels.cpp)

Note that since you don't want to use a filter but instead set the log level in the handler, there is the limitation that in the log file you will also see warnings, errors, etc but in the console you will see the limited log levels.

**Comment by odygrd** [comment]
This is now implemented in master, so closing this. Please let me know if you have any issues
