### ISSUE TITLE
Support one LogLevel multiple sinks.

### ISSUE THREAD

**Issue by FlameTornado10** [odygrd/quill#490]
Is it possible to log into different files even for logs of the same loglevel? I checked the examples but only find logging into different files possible when using different loglevels.

**Comment by odygrd** [comment]
Hey, not sure exactly what you are trying to achieve 

Do you mean something like this

  auto file_sink_a = quill::Frontend::create_or_get_sink<quill::FileSink>(
    "example_file_logging_a.log",
    []()
    {
      quill::FileSinkConfig cfg;
      cfg.set_open_mode('w');
 cfg.set_filename_append_option(quill::FilenameAppendOption::StartDateTime);
      return cfg;
    }(),
    quill::FileEventNotifier{});

  auto file_sink_b = quill::Frontend::create_or_get_sink<quill::FileSink>(
    "example_file_logging_b.log",
    []()
    {
      quill::FileSinkConfig cfg;
      cfg.set_open_mode('w');
 cfg.set_filename_append_option(quill::FilenameAppendOption::StartDateTime);
      return cfg;
    }(),
    quill::FileEventNotifier{});


  quill::Logger* logger =
    quill::Frontend::create_or_get_logger("root", {std::move(file_sink_a), std::move(file_sink_b)},
                                          "%(time) [%(thread_id)] %(short_source_location:<28) "
                                          "LOG_%(log_level:<9) %(logger:<12) %(message)",
                                          "%H:%M:%S.%Qns", quill::Timezone::GmtTime);

**Comment by FlameTornado10** [comment]
Just found that I make a mistake when calling create_or_get_logger, in which I pass the same logger_name two times. Then I pass separate logger_name when calling create_or_get_logger, and everything works.
```cpp
  g_logger_1 = quill::Frontend::create_or_get_logger(
      "g_logger_1", std::move(file_sink_1),
      "%(time) [%(thread_id)] "
      "LOG_%(log_level:<9) %(logger:<12) %(message)",
      "%H:%M:%S.%Qns", quill::Timezone::LocalTime);
  g_logger_2 = quill::Frontend::create_or_get_logger(
      "g_logger_2", std::move(file_sink_2),
      "%(time) [%(thread_id)] "
      "LOG_%(log_level:<9) %(logger:<12) %(message)",
      "%H:%M:%S.%Qns", quill::Timezone::LocalTime);
```

**Comment by odygrd** [comment]
Yes the logger name is used as a unique id, once the logger is created with that name then it returns you the same logger ignoring the rest parameters

**Comment by FlameTornado10** [comment]
Yeah I get it. Thank you for your reply and your amazing work
