### ISSUE TITLE
Unable to run cmake starting v4.0.0

### ISSUE THREAD

**Issue by dan1338** [odygrd/quill#491]
Hi, I tried building the latest master and the v4.5.0 release but in both cases it seems like cmake errors out.

Here is the log from cmake

```cmake
-- CMAKE_BUILD_TYPE: Release
-- QUILL_VERSION: 4.0.0
-- QUILL_NO_EXCEPTIONS: OFF
-- QUILL_NO_THREAD_NAME_SUPPORT: OFF
-- QUILL_X86ARCH: OFF
-- QUILL_DISABLE_NON_PREFIXED_MACROS: OFF
CMake Error at quill/CMakeLists.txt:115 (target_sources):
  target_sources may only set INTERFACE properties on INTERFACE targets


CMake Error at quill/CMakeLists.txt:151 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "VERSION" is not allowed.


CMake Error at quill/CMakeLists.txt:151 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "SOVERSION" is not allowed.


-- Configuring incomplete, errors occurred!
See also "/tmp/quill/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/quill/build/CMakeFiles/CMakeError.log".
```

I'm running cmake version 3.16.3 on ubuntu/wsl2.
First saw it happen when I added it via `add_subdirectory` but later tests on a fresh clone of the repo led me to v3.9.0 as the last working version.

Interestingly enough I haven't found any information about this online or in the issues so I might be overlooking something because it seems unlikely for it to have been unnoticed for that long.

**Comment by odygrd** [comment]
are you using a custom cmake for quill ? quill/CMakeLists.txt:115 seems outdated

it seems that you are using the old CMakeLists.txt ? v4.0.0 and onwards is header only and does not build as a static or shared library anymore

**Comment by dan1338** [comment]
Not really, I tried just cloning and running `cmake ..` and it fails
![image](https://github.com/user-attachments/assets/7ea7851b-483c-493f-bebb-fde9a31b2555)

**Comment by odygrd** [comment]
the behaviour of target_sources has changed since cmake 3.19 
https://cmake.org/cmake/help/latest/release/3.19.html

I can reproduce with cmake 3.16. It should work with newer versions after 3.19. 

I will try to see if a workaround is possible

**Comment by dan1338** [comment]
Good to know but also such a PITA
I'd suggest raising the cmake_minimum_required version, to 3.19 or whichever version corresponds best to the way target_sources is used in

**Comment by odygrd** [comment]
I have fixed this on https://github.com/odygrd/quill/pull/487/commits/59f6d0bd41faecdeddda5c4c3f9d5030025c987a which will be in the next release in the few days.
If you would like a workaround for now you can do something similar locally

Thanks for reporting this

**Comment by dan1338** [comment]
Yeah thanks for the quick response time.
I got myself cmake 3.29 from the official Kitware repo so I can build master, but the fix is welcome
