### ISSUE TITLE
short_source_location description wrong in documentation

### ISSUE THREAD

**Issue by AlemSnyder** [odygrd/quill#495]
The description given for short_source_location is "Full source file path and line number as a single string". It should be "Filename portion of path name and line number as a single string."

There is also inconsistent use of periods, and "Filename portion of pathname." should be "Filename portion of path name."

The last two are less important.

**Comment by odygrd** [comment]
thanks for reporting, should be fixed in https://github.com/odygrd/quill/commit/1f702b01e3074b289618151ddf76a014eb91746a
