### ISSUE TITLE
Enabling QUILL_NO_EXCEPTIONS on recommended usage adds -fno-exceptions to the entire project

### ISSUE THREAD

**Issue by tarun-t** [odygrd/quill#499]
Given that ```overwrite_macros.h``` includes ```LogMacros.h```, ```-fno-exceptions``` is added to anything that depends on the former I guess. Is there a workaround for this?

**Comment by odygrd** [comment]
thanks for reporting this, now that the library is header only we should remove this flag. This should be fixed in 7de4149b0d465344a81573dd02f0961427d6ac51

If it is still an issue after this commit, please let me know
