### ISSUE TITLE
How to add a file handler for default logger ?

### ISSUE THREAD

**Issue by zhangzq** [odygrd/quill#52]
e.g: 

```C++
auto logger = quill::get_logger();
logger->add_handler(file_handler);
```

Thx.

**Comment by odygrd** [comment]
Hello, it is possible to add your file handler to the default logger.
Please use `quill::set_default_logger_handler(file_handler);` 
https://github.com/odygrd/quill/blob/master/quill/include/quill/Quill.h#L232

Also this example might be helpful :

https://github.com/odygrd/quill/blob/master/examples/example_custom_formatter.cpp#L22

Let me know if you have any issues

**Comment by zhangzq** [comment]
Thanks.
