### ISSUE TITLE
Implement Shared Backend Thread for Multi-Process Logging

### ISSUE THREAD

**Issue by tarun-t** [odygrd/quill#533]
### Description

I propose enhancing the Quill logging library to allow multiple processes to share a single backend Process. This would involve using shared memory for inter-process communication and finding a way to share ```static constexpr``` metadata across processes.

### Proposed Implementation
1. Shared Backend Process:
   - Implement a mechanism to create a single backend process that can be accessed by multiple processes.
   - This thread would be responsible for processing log messages from all connected processes.

2. Shared Memory for Log Queue:
   - Use shared memory to implement a lock-free queue that all processes can write to.
   - The shared backend thread would read from this queue and process the log messages.

3. Sharing Static Constexpr Metadata:
    - Can't think of a way to share this data across processes. Is it possible?

I think this would probably require a major rewrite. Is this something that has been considered earlier?

**Comment by odygrd** [comment]
Hey,

Thanks for sharing this idea—it's a solid approach, and Iike the separation of concepts.

I find this design might be more suitable for a company looking to manage things internally. Sharing it across different platforms and requiring everyone to use shm would be more challenging.

This design does offer safer crash behavior, but at the cost of some speed in backend processing.

Here's some background:

Currently, Quill always encodes POD data for arguments. The only non-pointer data in the header are the `Metadata*` and `Logger*` information. Metadata is straightforward to create and share during program initialization as a file. While they won't be `constexpr` anymore, they can be static global variables initialized during static init time. Loggers can also be shared at runtime using file locks.

It’s possible to place everything in shared memory and decode from there. However, there’s a critical point to consider: Quill creates a templated decode function for each log statement and passes the function pointer to the background thread. This approach means there's no need to encode type information into the queue, which allows the backend thread to decode faster by avoiding conditional checks like `if` or `switch` statements.

Regarding the prototype:

About six months ago, I developed a prototype based on this concept. This is actually how the Frontend and Backend separation in Quill originated. I implemented Metadata initialization at startup and loggers, using just 1 byte for type information. While the initial benchmarks showed that frontend latency was close to Quill, the backend worker throughput was significantly lower—around 100% slower or more compared to Quill's template-based approach.

Another downside is that user-defined types can't be easily passed unless the backend thread is compiled with the same structures. 

Additionally, handling new programs starting and stopping, as well as registering new shared memory queues, requires considerable logic. The best solution might involve maintaining a TCP connection with each application to monitor their status.

This approach is primarily Linux-focused.

Moreover, there's the risk of a misbehaving process overwhelming the backend thread by logging excessively, which could unexpectedly slow down logging for other processes by filling up their queues.

If you're interested, here's a link to my prototype: [GitHub - bitlog prototype](https://github.com/odygrd/bitlog/tree/master). Feel free to explore and experiment with it.

**Comment by tarun-t** [comment]
Thanks for the reply, I'll go through bitlog. However, I believe the throughput on the background process in the shared memory context can be improved by making it busy-wait. So in the case where a large number of processes are writing at high-rates the number might in-fact be better than a single-core handling multiple threads.

**Comment by odygrd** [comment]
main1.cpp is the frontend and main2.cpp the backend. You can check it out it’s working but lacks many features and handling of edge cases and also using the filesystem
