### ISSUE TITLE
Adding metadata after printing a new line in Trivially Copyable structures

### ISSUE THREAD

**Issue by tarun-t** [odygrd/quill#534]
### Current Behavior

When using an ```operator<<``` overload to log user-defined types, the metadata (timestamp, log level, etc.) is only logged for the first line of output. Subsequent lines produced by the custom operator do not include this metadata.

### Desired Behavior

All lines of output produced by an ```operator<< ``` overload should include the appropriate metadata, maintaining consistency with single-line log entries.

**Comment by odygrd** [comment]
I've implemented this for the next release. It introduces an approximate 1.8% overhead in backend thread processing, which isn't that bad, so I'm enabling it by default.
