### ISSUE TITLE
Multiple Formatting Options for Trivially Copyable Structures

### ISSUE THREAD

**Issue by tarun-t** [odygrd/quill#536]
### Current Behaviour

Quill currently supports formatting trivially copyable structures off the hot path but is limited to a single formatting style per structure.

### Proposed Enhancement

Introduce support for multiple formatting options for trivially copyable structures that can be invoked from the hot path. Currently, I have to modify these structures to add an ```enum``` to indicate the style required. Is there a better way of doing it?

**Comment by odygrd** [comment]
Hey, not sure how easy it would to support this. It is using libfmt to format so if libfmt supports that it would be okay.

do you know if it’s possible to do that using libfmt ?

**Comment by tarun-t** [comment]
Yes, I've cooked up a short example demonstrating the same. [https://godbolt.org/z/Mve5bb5bb](url)

**Comment by odygrd** [comment]
That should also work in existing quill version if you use fmtquill namespace. 
can you please give it a try ?

**Comment by tarun-t** [comment]
Will do and report. I thought this might require changes in the ```Codec```. If it does work this could perhaps be added to the documentation.

**Comment by odygrd** [comment]
fmtlib syntax language is supported, the format string is passed to libfmt for formatting

**Comment by odygrd** [comment]
```c++
#include "quill/Backend.h"
#include "quill/Frontend.h"
#include "quill/LogMacros.h"
#include "quill/Logger.h"
#include "quill/sinks/ConsoleSink.h"

#include "quill/TriviallyCopyableCodec.h"
#include "quill/bundled/fmt/format.h"

#include <string>

struct Point {
  int x, y;
};

template <>
struct fmtquill::formatter<Point> {
  char presentation = 'p';

  constexpr auto parse(format_parse_context& ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin(), end = ctx.end();
    if (it != end && (*it == 'p' || *it == 'c')) {
      presentation = *it++;
    }
    if (it != end && *it != '}') {
      throw format_error("invalid format");
    }
    return it;
  }

  template <typename FormatContext>
  auto format(const Point& p, FormatContext& ctx) const -> decltype(ctx.out()) {
    switch (presentation) {
    case 'p':
      return fmtquill::format_to(ctx.out(), "({}, {})", p.x, p.y);
    case 'c':
      return fmtquill::format_to(ctx.out(), "x: {}, y: {}", p.x, p.y);
    default:
      throw format_error("invalid format");
    }
  }
};

template <>
struct quill::Codec<Point> : quill::TriviallyCopyableTypeCodec<Point>
{
};

int main()
{
  quill::BackendOptions backend_options;
  quill::Backend::start(backend_options);

  // Frontend
  auto console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>("sink_id_1");
  quill::Logger* logger = quill::Frontend::create_or_get_logger("root", std::move(console_sink));

  Point p{10, 20};
  LOG_INFO(logger, "Default format: {}\n", p);
  LOG_INFO(logger, "Parentheses format: {:p}\n", p);
  LOG_INFO(logger, "Coordinate format: {:c}\n", p);
}
```

**Comment by odygrd** [comment]
https://quillcpp.readthedocs.io/en/latest/cheat_sheet.html#introduction

> Quill uses libfmt for formatting, supporting the {} placeholders syntax (https://fmt.dev/latest/syntax).

This is mentioned in the documentation above. If you think it should also be added in a different section of the documentation let me know and i will add it :)

Also thanks for the example, I didn’t know you could do this with libfmt

**Comment by tarun-t** [comment]
Can confirm that this works. Thanks for testing it. I think the documentation added suffices. Closing this issue for now.
