### ISSUE TITLE
Run benchmark failed

### ISSUE THREAD

**Issue by oPiZiL** [odygrd/quill#54]
`BENCHMARK_quill_hot_path_rdtsc_clock `

> terminate called after throwing an instance of 'quill::QuillError'
  what():  failed to call set_cpu_affinity, with error message "Invalid argument", errno "22"
Aborted (core dumped)

**Comment by odygrd** [comment]
How many physical CPU cores does the system you are trying to run it has ?

The benchmark runs for 1 and 4 threads. 
For 1 thread it needs 2 different cores and for 4 threads it needs 5 cores. 
1 extra core is for the backend logging thread.

Can you please try again with setting under hot_path_bench_config.h

```
#define THREAD_LIST_COUNT std::vector<int32_t> { 1 }
```

and if this passes, then please try with 

```
#define THREAD_LIST_COUNT std::vector<int32_t> { 1, 2 }
```

**Comment by oPiZiL** [comment]
Hi, odygrd.
  Thanks for reply.  Works for me with 4 CPU cores.  
```
#define THREAD_LIST_COUNT std::vector<int32_t> { 1, 2 }
```

**Comment by odygrd** [comment]
Thanks, closing this and let me know if you have any other issues
