### ISSUE TITLE
Doxygen docs broken

### ISSUE THREAD

**Issue by chiefmigizi** [odygrd/quill#544]
When looking at the docs online or compiling yourself the Doxygen docs are broken. It looks like it may be an issue with namespace scoping.

Here is an example of the message you get when trying to view it from the online docs.

> doxygenstruct: Cannot find class “quill::BackendOptions” in doxygen xml output for project “Quill” from directory: build/xml

**Comment by odygrd** [comment]
Thanks for reporting. It seems that introducing the inline namespace in v6 has broken the docs

**Comment by odygrd** [comment]
it seems fixed now : )
