### ISSUE TITLE
Alternating file sink

### ISSUE THREAD

**Issue by simenallum** [odygrd/quill#545]
I am using the log output with the ELK stack, and I’ve noticed a problem with the current log rotation strategy. Filebeat, which is part of the ELK stack, identifies log files by inode and device name. When a logfile is rotated using a copy-and-truncate method, Filebeat can resend logs that have already been processed because it sees them as new files.

To avoid this issue, I suggest adding a new sink that alternates between two log files based on file size. This would work similarly to the SimpleFileChannel in Poco with rotation enabled:
- The application writes to one log file until it reaches a set size.
- When that file is full, logging switches to the second file.
- Once the second file is full, the first file is cleared and used again.

This method prevents inode changes and ensures that Filebeat does not resend log entries, making it a better fit for ELK stack users.

While I could implement this as a custom sink, I think it would be a valuable feature.

**Comment by odygrd** [comment]
Thanks for reporting, I will have a look on inode changes while renaming.

I haven’t used Filebeat but from the documentation here it seems possible to only watch the main log file and use exclude_files pattern for the rotated files or this isn’t an option ?

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html

**Comment by odygrd** [comment]
The file is renamed during rotation. The file name changes but the inode is still the same.

For example 
file. log -> node: 527528 

after rotation
file.log -> node: 528336
file_1. log -> node: 527528 

but file.log has only recent logs. The previous logs have a new filename but the inode is the old one so Filebeat shouldn’t see the remamed file as a new file if it is watching the inodes and there shouldn’t be any duplicated logs ?

**Comment by odygrd** [comment]
I attempted to reproduce the issue but was unable to do so. Here's what I did:

1. Installed Filebeat and configured it with the following input settings:

    ```yaml
    filebeat.inputs:
      - type: filestream
        id: my-filestream-id
        enabled: true
        paths:
          - /home/odygrd/logtest/*.log

    output.console:
      pretty: true
    ```

2. I used the example from [rotating_file_logging.cpp](https://github.com/odygrd/quill/blob/master/examples/rotating_file_logging.cpp) to log a line every second.

I've attached the logs generated by Filebeat for reference. After reviewing them, I did not observe any duplicated log entries.
[filebeat_logs.txt](https://github.com/user-attachments/files/16815610/filebeat_logs.txt)

**Comment by simenallum** [comment]
Hi! Thank you for the quick and thorough response. I hadn't integrated the Quill library yet and therefore hadn't tested the renaming behavior. I mistakenly assumed that renaming would change the inodes, but after testing, I can confirm that there are no inode changes and no duplicates in Kibana. Sorry for the confusion, and thanks again for your help!
