### ISSUE TITLE
Chrono duration type logging no longer supported

### ISSUE THREAD

**Issue by stephanie-eng** [odygrd/quill#547]
**Describe the bug**
In version 3, I was able to log a chrono duration in a message like this:
```
LOG_INFO(logger, "A message with a duration type {}",  std::chrono::seconds(1));
```

I updated to 6.1.2 and now get this error:

```
main.cc:21:3:   required from here
quill/include/quill/core/Codec.h:88:29: error: static assertion failed: Unsupported type
   88 |       static_assert(detail::always_false_v<Arg>, "Unsupported type");
```

Looking at the [Codec struct logic](https://github.com/odygrd/quill/blob/1401d2d90f85a6b83ab1b259590d8ba227446a92/quill/include/quill/core/Codec.h#L62-L89), are duration types no longer supported?

**To Reproduce**
Steps to reproduce the behaviour if possible
```
#include <chrono>
#include <string>
#include <utility>

#include "quill/Backend.h"
#include "quill/Frontend.h"
#include "quill/LogMacros.h"
#include "quill/Logger.h"
#include "quill/sinks/ConsoleSink.h"

int main() {
  quill::BackendOptions backend_options;
  quill::Backend::start(backend_options);

  // Frontend
  auto           console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>("sink_id_1");
  quill::Logger* logger = quill::Frontend::create_or_get_logger("root", std::move(console_sink));

  std::chrono::seconds t(1);
  LOG_INFO(logger, "A message with a duration type {}", t);
}
```

**Expected Behaviour**
Chrono types do not cause errors

**Environment**
- Operating System: Ubuntu
- Compiler: gcc 11.4.0

**Comment by odygrd** [comment]
It should work if you include quill/std/Chrono.h 
To log stl types you need to include the relevant headers

From v4 and onwards the library changed to have minimal includes and also copy only POD data, therefore explicit support is needed for each type.

please try again and let me know

**Comment by stephanie-eng** [comment]
Thank you, this solved my issue.
