### ISSUE TITLE
1 test fails: rotating_file_sink_index_open_mode_write_clean_up_old_files

### ISSUE THREAD

**Issue by yurivict** [odygrd/quill#550]
**Describe the bug**
```
44/161 Testing: rotating_file_sink_index_open_mode_write_clean_up_old_files
44/161 Test: rotating_file_sink_index_open_mode_write_clean_up_old_files
Command: "/usr/ports/devel/quill/work/.build/build/test/TEST_RotatingFileSink" "--test-case=rotating_file_sink_index_open_mode_write_clean_up_old_files"
Directory: /usr/ports/devel/quill/work/.build/test/unit_tests
"rotating_file_sink_index_open_mode_write_clean_up_old_files" start time: Sep 05 23:34 PDT
Output:
----------------------------------------------------------
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
/usr/ports/devel/quill/work/quill-7.0.0/test/unit_tests/RotatingFileSinkTest.cpp:202:
TEST SUITE: RotatingFileSink
TEST CASE:  rotating_file_sink_index_open_mode_write_clean_up_old_files

/usr/ports/devel/quill/work/quill-7.0.0/test/unit_tests/RotatingFileSinkTest.cpp:239: FATAL ERROR: REQUIRE( !fs::exists(filename_2) ) is NOT correct!
  values: REQUIRE( false )

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 20 skipped
[doctest] assertions: 7 | 6 passed | 1 failed |
[doctest] Status: FAILURE!
```

**Environment**
- Operating System: FreeBSD 14.1
- Compiler: clang-18

**Comment by odygrd** [comment]
hey, thanks for reporting. I can not preproduce on freebsd with gcc 13

There should be no changes there compared to the previous version. Can you please maybe try to rerun it ?

<img width="356" alt="image" src="https://github.com/user-attachments/assets/76d858c1-ff81-428e-856f-862fe433eb68">

**Comment by yurivict** [comment]
When the system is loaded some tests fail intermittently.
This likely means that race conditions exist.

![image](https://github.com/user-attachments/assets/e12a60c6-1d78-4d77-8b1e-1ec8dbcae7c9)

**Comment by odygrd** [comment]
There are few tests making some assumptions. This is one of those tests expecting a loop to run N times but it won’t run N times if the system is busy. They are mainly designed to run on github actions or the user running them manually

**Comment by odygrd** [comment]
‘multi_frontend_threads’ and ‘user_sink’ tests might be unstable depending on the system load. 
The rest should be stable, not sure how the RotatingFileSink one failed as i haven’t seen it failing before

**Comment by odygrd** [comment]
I have stabilised those tests in https://github.com/odygrd/quill/pull/551
I tested on freebsd with `stress --cpu 2000 --timeout 120 &` and they are passing on VM
Will be in release `7.0.1` in a few days. If you have any issues after this release let me know
