### ISSUE TITLE
Portion of pattern after %(message) is ignored if it contains no format specifiers

### ISSUE THREAD

**Issue by sandyharvie** [odygrd/quill#56]
To provide an example, if the pattern is `%(level_name)|%(message)|EOM`, `LOG_INFO("this is a log message")` currently produces `INFO     |this is a log message` instead of `INFO     |this is a log message|EOM`.

**Comment by sandyharvie** [comment]
See https://github.com/odygrd/quill/pull/57 for a fix.

**Comment by odygrd** [comment]
thanks a lot for reporting this
