### ISSUE TITLE
Short codes incorrect for levels above Info

### ISSUE THREAD

**Issue by danmou** [odygrd/quill#564]
**Describe the bug**
The log level is incorrect when using `%(log_level_short_code)` in the formatter, for example `LOG_ERROR` gives `"C"` and `LOG_WARNING` gives `"E"`.

**Additional context**
I tracked down the problem, it was introduced in #526 which didn't add an element to the `log_level_short_codes` array:

https://github.com/odygrd/quill/blob/e11d26e0ca674832fe696503aaa2ff91360696bc/include/quill/backend/BackendOptions.h#L217-L218

Simply adding `"N"` to that list would solve it, but that would lead to ambiguity with `None` so I'm not sure what's the best choice.

**Comment by odygrd** [comment]
Thanks for catching this. None can not be displayed in the log file so we can use any value there. I will get this fixed today for the next release

**Comment by odygrd** [comment]
until the next release, as the workaround you can use the `log_level` instead and overwrite it

For example

```c++
  quill::BackendOptions backend_options;
  backend_options.log_level_descriptions = {"T3", "T2", "T1", "D",  "I", "N",
                                            "W",  "E",  "C",  "BT", "_", "DN"};
  quill::Backend::start(backend_options);

  auto console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>("sink_id_1");

  quill::PatternFormatterOptions pfo;
  pfo.format_pattern =
    "%(time) [%(thread_id)] %(short_source_location:<28) %(log_level) %(logger:<12) %(message)";
  quill::Logger* logger = quill::Frontend::create_or_get_logger("root", std::move(console_sink), pfo);
```
