### ISSUE TITLE
Custom Datetime format for set_filename_append_option(Datetime)

### ISSUE THREAD

**Issue by QuillUsr1** [odygrd/quill#571]
Currently I can use `set_file_append_option(quill::FilenameAppendOption::StartDateTime);` which appends the datetime in a fixed format to the filename e.g `YYYYMMDD_HHmmss`. It would be nice to have control over the formatting here, and add the ability to include the micros.

**Comment by odygrd** [comment]
hey, 

for the `FileSink` that would be easy to add

For the `RotatingFileSink` it is a bit more difficult to add as it is has logic to search/clean previous files

**Comment by odygrd** [comment]
actually it should be fine for the rotating one as well
