### ISSUE TITLE
Compilation failes with -fno-rtti

### ISSUE THREAD

**Issue by alphanso** [odygrd/quill#604]
**Describe the bug**
I am using quill v3.8. I am using it with -fno-exception -fno-rtti. I am trying to migrate to v7.3. It uses dynamic_cast which is not allowed with -fno-rtti. 

**To Reproduce**
Compile with -fno-rtti

**Expected Behaviour**
I was expecting it to compile without errors with -fno-rtti

**Environment**
Linux

Btw, thanks for this library. I have been using it for years.

**Comment by odygrd** [comment]
thanks for reporting : ) There will be a fix merged in master soon. Are you able to use master for now without a new release ?
