### ISSUE TITLE
Multiple Sinks for a Single Logger Not Working

### ISSUE THREAD

**Issue by ottoborden** [odygrd/quill#608]
**Describe the bug**
The docs state: "When creating a logger, one or more sinks for that logger can be specified. Sinks can only be registered during the logger creation." And I can see that the `Frontend::create_or_get_logger()` method takes a `std::initializer_list` of Sinks. However I have not been able to get a logger that will log to both console and a file.

**To Reproduce**
```
#ifdef NDEBUG
#else
#define QUILL_IMMEDIATE_FLUSH true
#define QUILL_COMPILE_ACTIVE_LOG_LEVEL QUILL_COMPILE_ACTIVE_LOG_LEVEL_TRACE_L3
#endif

....

  // log everything to console
  auto console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>(
      "console_sink");
  // log everything to file
  auto file_sink = quill::Frontend::create_or_get_sink<quill::FileSink>(
      "debug_logs.txt", []() {
        quill::FileSinkConfig cfg;
        cfg.set_open_mode('w');
        cfg.set_filename_append_option(
            quill::FilenameAppendOption::StartDateTime);
        return cfg;
      }(),
      quill::FileEventNotifier{});
  // create logger
  quill::Logger *logger = quill::Frontend::create_or_get_logger(
      "root", {std::move(console_sink), std::move(file_sink)});
  logger->set_log_level(quill::LogLevel::TraceL3);
```

**Expected Behaviour**
I would expect it to log to both sinks concurrently. However, with the code above, I only see the logs in the console. The `debug_logs.txt` file does get created, but it is empty. If I remove the `std::move(console_sink)` in the code above it logs to the file as expected.

**Environment**
- Operating System: Windows 11
- Compiler: Microsoft Visual C++ 2022, MSVC 19

**Additional context**
None that would be useful. I'm using a custom memory allocator (mi-malloc) but I can't imagine that is an issue here.

**Comment by odygrd** [comment]
Hey, that is surprising we have a test for this and is currently passing all CI

https://github.com/odygrd/quill/blob/412051106e2a89865bb1158f30609ce5bb98de6e/test/integration_tests/MultipleSinksSameLoggerTest.cpp#L49

I will try with the sample code you provided and let you know

**Comment by odygrd** [comment]
I have tried debug/release builds for static and shared library and can not reproduce on MSVC 19.39.33523.0

https://github.com/odygrd/quill/compare/v7.3.0...7.3.0_issue608

For static linking :

https://github.com/odygrd/quill/blob/7.3.0_issue608/examples/console_logging.cpp

For shared library

https://github.com/odygrd/quill/tree/7.3.0_issue608/examples/shared_library

**Comment by odygrd** [comment]
can this be related to this https://github.com/odygrd/quill/issues/479 ?

Are you using an old version like `4.0.0` that had a bug there ?
