### ISSUE TITLE
[feature request] Add option for replacing '::' with '.' in %(function_name) formatter

### ISSUE THREAD

**Issue by bl-ue** [odygrd/quill#61]
When I have a function several namespaces deep, the `::` symbol becomes hard to read when outputted line after line, several times in each line.  It would be nice to be able to specify an option to replace `::` with a `.`.

**Comment by odygrd** [comment]
Hello,

`%(function_name)` is using `__FUNCTION__`, I don't see any `::` when i use it even if the function is under namespaces. 

Which operating system are you using ? Can you please give me an example of the log message you are seeing and what you would like to replace ?

**Comment by bl-ue** [comment]
Hi @odygrd, I didn't realize that the namespaces in the `__FUNCTION__` macro expansion is an MSVC-only feature. I'm using Windows 10 and Visual Studio 2019.

**main.cpp**
```cpp
#include "quill/Quill.h"

quill::Handler* handler = quill::stdout_handler();
quill::Logger* logger = quill::create_logger("logger", handler);

namespace a
{
namespace b
{
namespace c
{
namespace d
{
void Example()
{
  LOG_INFO(logger, "Example");
}
}
}
}
}

int main()
{
  // Start the logging backend thread
  quill::start();

  handler->set_pattern(QUILL_STRING("%(message) - at %(function_name) (%(filename):%(lineno))"));

  a::b::c::d::Example();
}
```

The program produces the following output on Windows:
```
Example - at a::b::c::d::Example (example_backtrace.cpp:14)
```

**Comment by odygrd** [comment]
This is done in master in df4a071bd7a5e5131e6b880d08bf95d484e1f8bb
Please let me know if you have any issues
