### ISSUE TITLE
Can we release quill on ROS 2 distributions?

### ISSUE THREAD

**Issue by saikishor** [odygrd/quill#613]
Hello!

Thank you for all the great work. Quill is one of the best loggers we came across. We would like to introduce this amazing logger to the community of ROS 2. Either you can release this on ROS 2 distributions or we can take care of the releases by fetching the upstream automatically and wrapping it into the package. Can you please let me know, which of the above option is better for you?.

Eventually, we would like to use it within the [ros2_control](https://github.com/ros-controls/ros2_control) architecture.

Thank you!

**Comment by odygrd** [comment]
Hello,

Thank you for your kind words about Quill ! I'm glad to hear about your interest in integrating it with ROS 2. I would prefer that you manage the releases.

Please feel free to reach out if you encounter any issues or need assistance with the library.

**Comment by saikishor** [comment]
Hello!

Thank you so much for helping us with this. I will take care of the releases and all. I've a question on the releases. Are you planning to maintain 0.7.x longer or do you have plans for 0.8.0 already?

Thank you!
