### ISSUE TITLE
log level none not supported by console sink

### ISSUE THREAD

**Issue by QuillUsr1** [odygrd/quill#619]
**Describe the bug**
When using console sink with colours, logging using log_none fails.
`fwrite failed errno: 14 error: Bad address`
**To Reproduce**
1. Create a console sink with colours
2. log using loglevel::none : `QUILL_LOGGER_CALL(QUILL_UNLIKELY, logger, nullptr, quill::LogLevel::None, fmt, ##__VA_ARGS__)`

**Expected Behaviour**
I expect to see my log.
Instead I get:
`fwrite failed errno: 14 error: Bad address`.

**Environment Details**
  - Quill 7.2.1 (but from the source code, this is present in the latest release too)

**Additional context**
This problem can be solved by changing the size of the colours array to 11 (or 12 to include dynamic?).
`std::array<std::string_view, 10> _colours; /**< Colours per log level */`
and adding a default colour

**Comment by odygrd** [comment]
Hey, thanks for reporting. LogLevel None purpose is part of the enum so that you can pass it to `set_log_level()` and disable all logging in runtime. It is not expected to be logged as part of a log statement

**Comment by odygrd** [comment]
I see it works after changing the array size
