### ISSUE TITLE
It is recommended to rename PACKED(fmt/base.h) to other name(like QUILLPACKED) to avoid conflicts 

### ISSUE THREAD

**Issue by IamHuskar** [odygrd/quill#620]
include/quill/bundled/fmt/base.h:1626:54: error: expected ‘>’ before ‘)’ token
template <bool PACKED, typename Context, typename T, FMTQUILL_ENABLE_IF(!PACKED)>

PACKED is commonly used at linux enviroment for memory align
#define PACKED __attribute__((__packed__))

**Comment by odygrd** [comment]
thanks for reporting this, I see it doesn't existing anymore in `fmt` master. For now it has been renamed
