### ISSUE TITLE
Not worked with CSI sequence or UTF-8

### ISSUE THREAD

**Issue by tqolf** [odygrd/quill#633]
**Describe the bug**

log macros don't work as expected with CSI sequence and Unicode.

https://godbolt.org/z/vGa11M591

**Comment by odygrd** [comment]
Hey, currently only utf-8 is supported

**Comment by odygrd** [comment]
Also note that the backend is sanitising by default non printable characters:

https://github.com/odygrd/quill/blob/36ff1c007e54a3b68cc8a78485d4e0c8850eab63/include/quill/backend/BackendOptions.h#L199

you can disable it like this and this might work for your example:

https://godbolt.org/z/76qGqETaY

**Comment by tqolf** [comment]
Thanks
