### ISSUE TITLE
How to change timestamp format in the JSON-formatted console message?

### ISSUE THREAD

**Issue by ksqrtr** [odygrd/quill#636]
Hi!
I'd like to use more human readable format like RFC 3339. Is it possible?

**Comment by odygrd** [comment]
For v7 you need to implement your own custom json sink with the desired formatting 

copy paste this class 
https://github.com/odygrd/quill/blob/master/include/quill/sinks/JsonFileSink.h

Or this class

https://github.com/odygrd/quill/blob/master/include/quill/sinks/JsonConsoleSink.h

And provide your own formatting eg here

https://github.com/odygrd/quill/blob/25389ad6a7c704127525a4004656bc3cb6a38aa0/include/quill/sinks/JsonConsoleSink.h#L74

Here is an example using a custom sink (in your case the copy pasted json sink)

https://github.com/odygrd/quill/blob/25389ad6a7c704127525a4004656bc3cb6a38aa0/examples/user_defined_sink.cpp#L81


There is an implemented change for v8 that lets you customise that without having to duplicate (https://github.com/odygrd/quill/blob/e6415fc541a3836a44d4280a1a654ba47dc027e9/include/quill/sinks/JsonSink.h#L101), but i am planning to release it in the next few months so I’d recommend just doing the above for now

Let me know if you need any further help

**Comment by ksqrtr** [comment]
Thanks a lot, I'll do what you have suggested till v8 is released.
BTW, do you have any plans to implement RotatedJsonFileSink?
