### ISSUE TITLE
calculation should ignored when should_log() = false

### ISSUE THREAD

**Issue by zhangzq** [odygrd/quill#67]
e.g. 

```C++
std::string very_cost_calc() {
    // ...
    return "costly result";
}

LOG_TRACE("{}", very_cost_calc());
```

When we set log level in info, then the `very_cost_calc()` shouldn't be called.

The problem is `check_format(FMT_STRING(fmt), ##__VA_ARGS__);` in  `QUILL_LOGGER_CALL`. We need to remove or fix the implement.

**Comment by odygrd** [comment]
Thanks for reporting. I see that `check_format` is not actually constexpr. If you have any ideas how to fix this let me know, I will also look into it over the next few days
