### ISSUE TITLE
Compilation for __ARM_ARCH < 6

### ISSUE THREAD

**Issue by TillAlex** [odygrd/quill#78]
Currently quill does not compile for __ARM_ARCH < 6 because x86 intrinsics are used in rdtsc.h. Using chrono clock does not help. Perhaps defaulting to chrono clock in this case is a solution.

**Comment by odygrd** [comment]
Thanks for reporting this. Can you please try with latest master, it should not include x86intrist

**Comment by TillAlex** [comment]
Thanks! Building for ARMv5 works now.

**Comment by odygrd** [comment]
Not able to test it. 
@TillAlex system clock is used instead of rdtsc for ARMv5 now, but are the log timestamps correct ?

**Comment by TillAlex** [comment]
Just testet it on my ARMv5 board and timestamps are ok. Quick tests show a latency (or resolution?) around 5 µs.
