### ISSUE TITLE
Update bundled fmt to 7.1.3

### ISSUE THREAD

**Issue by bl-ue** [odygrd/quill#81]
[{fmt} 7.1.3 was released](https://github.com/fmtlib/fmt/releases/tag/7.1.3), fixing https://github.com/fmtlib/fmt/issues/2011, and potentially removing the need for the workaround you added because of https://github.com/microsoft/vcpkg/issues/14331, see commit 5a4dbedd2e59249719f0053b86f521c2b8cfca83.

**Comment by odygrd** [comment]
Done in 7e3a93c7bb3f13692c88c3752a8b6ea85a807166
Commit message version is wrong
