### ISSUE TITLE
constexpr strlength on msvc c++20

### ISSUE THREAD

**Issue by niclar** [odygrd/quill#83]
Quill 1.6.0

This function and cousins bails for long runtime strings (fills the stack) under Visual Studio 2019 (Version 16.9.0 Preview 1.0)  Debug Build   (/std:c++latest) and clang 11 --std=c++20

QUILL_NODISCARD constexpr size_t strlength(char const* str)
{
  return *str ? 1 + strlength(str + 1) : 0;
}

**Comment by odygrd** [comment]
Thanks for reporting this!

**Comment by odygrd** [comment]
There is a fix in master, please let me know if it is still an issue and re-open
