### ISSUE TITLE
1.6.1 on CCI?

### ISSUE THREAD

**Issue by bl-ue** [odygrd/quill#87]
Hi @odygrd, will you please add the latest quill version 1.6.1 to the [conan-center-index](https://github.com/conan-io/conan-center-index)?  I'm still using Quill :smile:, but I moved from vcpkg to conan a few months ago and I'd like to use the latest version.

**Comment by bl-ue** [comment]
It would be nice if you had a script to auto-update quill on Homebrew/vcpkg/conan, etc...

**Comment by odygrd** [comment]
Hey, I will add `1.6.1` to package managers over the new few days

**Comment by bl-ue** [comment]
Thank you Odysseas ❤️

**Comment by odygrd** [comment]
Added PR for `1.6.1` on conan-center-index
