### ISSUE TITLE
Add CMAKE_INSTALL_PREFIX in README for installation directory?

### ISSUE THREAD

**Issue by azuresigma** [odygrd/quill#9]
This is to save some users(who didn't know cmake well enough) some google time for this CMake feature. My first google solution is 'make DESTDIR=/home/john install', then /usr/local is still created under /home/john. Not a big deal, I manually copied them from /home/john/usr/local. 

My current google solution is 'cmake -DCMAKE_INSTALL_PREFIX=/home/john/quill-1.0/'. I didn't try the command as my installation was done. It will be nice to add this to README if it works.

**Comment by odygrd** [comment]
Added - thanks!
