### ISSUE TITLE
file_handler/rotating_file_handler with MinGW-32

### ISSUE THREAD

**Issue by Schoppenglas** [odygrd/quill#92]
I'm having problems with the (rotating)_file_handler.

When trying quill::file_handler("my.log", "a") or quill::file_handler(L"my.log", "a") this error occur:
`Invalid parameter passed to C runtime function.`
`terminate called after throwing an instance of 'quill::QuillError`
`what():  fopen failed with error message errno: "22"`

MinGW, 32bit, Windows10

**Comment by Schoppenglas** [comment]
quill::file_handler("D:\\my.log", "a") or quill::file_handler(L"D:\\my.log", "a") also won't do the job.

**Comment by bl-ue** [comment]
@Schoppenglas You may need to specify `L"D:\\my.log"` with two slashes to escape it.

**Comment by Schoppenglas** [comment]
> 
> 
> @Schoppenglas You may need to specify `L"D:\\my.log"` with two slashes to escape it.

I've written it with two slashes, github supresses one of them.

**Comment by bl-ue** [comment]
error `22` is something to do with invalid characters 🤔 https://stackoverflow.com/questions/25584124/oserror-errno-22-invalid-argument-when-use-open-in-python

**Comment by Schoppenglas** [comment]
> 
> 
> error `22` is something to do with invalid characters 🤔 https://stackoverflow.com/questions/25584124/oserror-errno-22-invalid-argument-when-use-open-in-python

It doesnt even work with "my.log" / L"my.log". No Invalid characters at all.

**Comment by bl-ue** [comment]
Hmm. I wonder if quill is adding bad characters to the name.

**Comment by Schoppenglas** [comment]
I can confirm that in quill::detail::fopen(filename_t const& filename, std::string const& mode) the parameter mode wont correctly converted to std::wstring.

**Comment by odygrd** [comment]
Hey, thanks for looking into this and for PR, I've merged it. Let me know if you have any more issues
