### ISSUE TITLE
Add thread attribute

### ISSUE THREAD

**Issue by dskachan** [odygrd/quill#97]
Hello there. 
That would be very nice if Quill will get the ability to add thread attribute. 
I have multithreading applications, and yes, there is a thread Id for such purposes. 
But it is much more comfortable to have user-defined tags for threads, which might be used as aliases for threads. (such option have e.g. boost logger) 

that might be used so:
in a thread
```
logger->set_thread_attribure("ThreadName","thread1"); // must be execude in the thread, which must have this attribute. 
```
then it might go to the formatted like that:
```
file_handler->set_pattern(
    QUILL_STRING("<%(level_name)> [%(ThreadName)] %(function_name): %(message)"), // log recorder format
    "%H:%M:%S.%Qns");
```
so, one will have a message at the end: 
```
<LOG_DEBUG> [thread1] foo: my lovely message
```

**Comment by odygrd** [comment]
Hey, thanks for the idea. I agree a thread name instead of the thread id could be useful in certain cases for example if you wanted to compare logs between runs etc..

I think i would just prefer to add a `thread_name` in the `set_pattern` string. That would mean that you need to set the thread name yourself first and afterwards that would be retrieved and used in the log.

Would that be sufficient ?

**Comment by odygrd** [comment]
This is done in #101 

You must set the name of the thread prior to issuing any log statement on that thread.

There is also an example here : https://github.com/odygrd/quill/blob/master/examples/example_custom_formatter_thread_name.cpp

Please let me know if you have any more issues

**Comment by dskachan** [comment]
Oh. cool! I will check it out! thanks a lot!

**Comment by dskachan** [comment]
Hello there!
that works as expected!
will that be included in the next tag? 
would use it over conan center

**Comment by odygrd** [comment]
Hey, yes it will be part of the next release and available in conan. 
I don't have an estimate for the next release. 
I think I can do one over the next 1-2 weeks so that feature is included
