### ISSUE TITLE
add custom severity level

### ISSUE THREAD

**Issue by dskachan** [odygrd/quill#98]
is that be possible to add a custom severity level? 
maybe displace all levels with own.

**Comment by odygrd** [comment]
The log levels are defined as an enum in compile time and right now it is not possible to have a custom severity level ? 
What functionality exactly are you trying to achieve ?

**Comment by dskachan** [comment]
I have two goals. Which might look weird. 
First of all, is development. I have a pretty big application with lots of modules, which write logs. Moreover, it is known that lower severity levels (e.g. trace or debug) causing not optimal behavior. 
So, If I need to change the legacy part of the code, or integrate a new one, I have one more level with the highest severity - LOG_CURRENT_DEBUG. so I can see messages of currently developed modules, even on higher levels of severity (in optimal performance of the application). For sure, LOG_CURRENT_DEBUG is not the logs, which are merged into the master branch. They are for bug fixing and development only. 

Secondly, I would like to have the ability to change the representation of the severity in the log. 
for example instead of "LOG_DEBUG" - Simply "DEBUG". I mean  "LOG_"  is really redundant. My application in the bad days may have tens of millions of lines, which means 40 MBytes are only devoted to "LOG_" per 10 Million lines. 
In my current logging, I even have "INFO; DEBG; WARN; TRCE; ERRO" etc. - but this is already сreepy.

**Comment by odygrd** [comment]
I am not sure how easy it will be to support custom log levels, will need to think about it first if it is possible with the current design.

With regards to your goals I would suggest the following workarounds :


1) 

a. If you don't mind slightly refactoring your application, another way of doing this would be each module to have it's own logger* object.

That way you would have fine control of which module is logging and which one is not logging and you would be able to control and change the logging of each module at anytime even while the application is running.

In Quill you can retrieve a previously created logger object. 
Ideally each class in your module would store a pointer to that logger object (this is to avoid looking up the logger* when you want to log).
The logger object is thread safe, so any thread can modify log_level which would affect what is logged by the module.

This usually what I would do for large applications as when they grow you always need some control over logging. It has the overhead of having to store a pointer to a logger in most of your classes and also you need to link the logger to almost everything even low level libraries as they need to have a `logger*` to log. e.g if `library_d::foo()` is called by both `module_a` and `module_b` then the `logger*` has to be provided by the caller (module_a or module_b) to `library_d:foo()`

```c++
namespace a
{
void init()
{
  quill::create_logger("module_a");
}

void foo()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_a");
  LOG_INFO(logger, "log from foo");
}

void bar()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_a");
  LOG_INFO(logger, "log from bar");
}
}

namespace b
{
void init()
{
  quill::create_logger("module_b");
}

void foo()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_b");
  LOG_INFO(logger, "log from foo");
}

void bar()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_b");
  LOG_INFO(logger, "log from bar");
}
}

int main()
{
  // Get the stdout file handler
  quill::Handler* file_handler = quill::stdout_handler();

  file_handler->set_pattern(
    QUILL_STRING("%(ascii_time) [%(thread)] %(fileline:<28) %(level_name) %(logger_name:<12) - %(message)"));

  quill::set_default_logger_handler(file_handler);

  quill::start();
  a::init();
  b::init();

  // Log from all modules
  a::foo();
  a::bar();
  b::foo();
  b::bar();

  // change module a logging level
  quill::get_logger("module_a")->set_log_level(quill::LogLevel::Error);
  
  // Only module b will log
  a::foo();
  a::bar();
  b::foo();
  b::bar();

}
```

b. There is another way that you can achieve this. That is you log everything but you have the backend logging thread filtering the results. 

Quill supports filters, therefore you can do the following to filter out logs from a certain module : 
(see also https://github.com/odygrd/quill/blob/master/examples/example_filters.cpp)

```c++
namespace a
{
void init()
{
  // Retrieve the stdout_handler that contains our filter
  quill::Handler* stdout_handler = quill::stdout_handler("stdout_1");
  quill::create_logger("module_a", {stdout_handler});
}

void foo()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_a");
  LOG_INFO(logger, "log from foo");
}

void bar()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_a");
  LOG_INFO(logger, "log from bar");
}
}

namespace b
{
void init()
{
  // Retrieve the stdout_handler that contains our filter
  quill::Handler* stdout_handler = quill::stdout_handler("stdout_1");
  quill::create_logger("module_b", {stdout_handler});
}

void foo()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_b");
  LOG_INFO(logger, "log from foo");
}

void bar()
{
  // retrieves existing logger, ideally cached as a class member to avoid the logger lookup each time
  auto* logger = quill::get_logger("module_b");
  LOG_INFO(logger, "log from bar");
}
}

/**
 * Filter for the stdout handler
 */
class StdoutFilter : public quill::FilterBase
{
public:
  StdoutFilter() : quill::FilterBase("StdoutFilter"){};

  QUILL_NODISCARD bool filter(char const* thread_id, std::chrono::nanoseconds log_record_timestamp,
                              quill::LogMacroMetadata const& metadata,
                              fmt::memory_buffer const& formatted_record) noexcept override
  {
    // filter module_b
    std::string_view fr { formatted_record.data(), formatted_record.size() };
    return fr.find("module_b") == std::string::npos;
  }
};

int main()
{
  // Start the logging backend thread
  quill::start();

  // Create an stdout_handler with our custom filter
  quill::Handler* stdout_handler = quill::stdout_handler("stdout_1");
  stdout_handler->add_filter(std::make_unique<StdoutFilter>());

  a::init();
  b::init();

  // Log all, but module_b is filtered out in the StdoutFilter
  a::foo();
  a::bar();
  b::foo();
  b::bar();

  LOG_INFO(quill::get_logger(), "done");
}
```

2) `LOG_` prefix is useful when grepping log files. For example the word `error` is common between libraries and many libraries can log it in the code. Imagine if you just wanted to grep all the error messages you logged and avoid all this noise in the log, you can just grep for `LOG_ERROR`. This is why it is the default behaviour in the logger. It is easy to change this.

The default logging pattern is : 
`"%(ascii_time) [%(thread)] %(fileline:<28) LOG_%(level_name) %(logger_name:<12) - %(message)"`

As you can notice there is a `LOG_` there. All you have to do is to define your own logging pattern, eg : 
`"%(ascii_time) [%(thread)] %(fileline:<28) %(level_name) %(logger_name:<12) - %(message)"`

You can customise it to be an even smaller string by logging less information, if you want to save more disk space.
(see https://github.com/odygrd/quill/blob/master/examples/example_custom_formatter.cpp)

```c++
int main()
{
  // Get the stdout file handler
  quill::Handler* file_handler = quill::stdout_handler();

  file_handler->set_pattern(
    QUILL_STRING("%(ascii_time) [%(thread)] %(fileline:<28) %(level_name) %(logger_name:<12) - %(message)"));

  quill::set_default_logger_handler(file_handler);

  quill::start();

  quill::get_logger()->set_log_level(quill::LogLevel::TraceL3);
  LOG_INFO(quill::get_logger(), "The default logger is using a custom format");
  LOG_DEBUG(quill::get_logger(), "The default logger is using a custom format");
}
```

**Comment by dskachan** [comment]
Hey, thanks a lot. 
you touched exactly the point I'm struggling on. 
yes, I came to the conclusion, that a singleton logger is not the thing, which will cover my need in my library. 
Especially this point: 

> This usually what I would do for large applications as when they grow you always need some control over logging. It has the overhead of having to store a pointer to a logger in most of your classes and also you need to link the logger to almost everything even low level libraries as they need to have a logger* to log. e.g if library_d::foo() is called by both module_a and module_b then the logger* has to be provided by the caller (module_a or module_b) to library_d:foo()

It is not a big issue to add a pointer on the logger to classes, which require logs. But to have a proper way to pass the pointer to the class... that only means that constructors of all major structures require adding some **logger pointer** or **tag name** of the module. I personally do not find this attractive but looks like I will not overcome this If I want my library to be used many times in a single application. I guess there is no other alternative if I want to have separate logging of my lib in several modules, isn't it? 
I will try to explain with an example: 
I mean this structure:
```
namespace lib{
struct LibStruct{
    void foo(){
    // here write log. 
    }
}
} //namespace lib
namespace user1{
struct User1{
lib::LibStruct ls{};
void bar{
  ls.foo();
}
}
} //namespace user1

namespace user2{
struct User2{
lib::LibStruct ls{};
void bar{
  ls.foo();
}
}
} //namespace user2

int main(){
//logging init. 

user1::User1 u1{};
user2::User2 u2{};

u1.bar();
u2.bar();
}

```

in this case, if I have the logging init in LibStruct - ```quill:get_logger("libStruct")```, I will have all logs in the same sink. 
If I will make logging in User's e.g. constructor ```quill:get_logger("user1")```, I will have to pass the pointer of the logger to the lib and pass it to all structures which are under the LibStruct. as an alternative I can pass the string "user1" to libStruc, so it will pass this name to down hierarchy classes, so, they may pick up logger they need. 


so, to the points: 
1.

**Comment by dskachan** [comment]
Hey, thanks a lot. 
you touched exactly the point I'm struggling on. 
yes, I came to the conclusion, that a singleton logger is not the thing, which will cover my need in my library. 
Especially this point: 

> This usually what I would do for large applications as when they grow you always need some control over logging. It has the overhead of having to store a pointer to a logger in most of your classes and also you need to link the logger to almost everything even low level libraries as they need to have a logger* to log. e.g if library_d::foo() is called by both module_a and module_b then the logger* has to be provided by the caller (module_a or module_b) to library_d:foo()

It is not a big issue to add a pointer on the logger to classes, which require logs. But to have a proper way to pass the pointer to the class... that only means that constructors of all major structures require adding some **logger pointer** or **tag name** of the module. I personally do not find this attractive but looks like I will not overcome this If I want my library to be used many times in a single application. I guess there is no other alternative if I want to have separate logging of my lib in several modules, isn't it? 
I will try to explain with an example:
```c++
namespace lib{
struct LibStruct{
    void foo(){
    // here write log. 
    }
}
} //namespace lib
namespace user1{
struct User1{
lib::LibStruct ls{};
void bar{
  ls.foo();
}
}
} //namespace user1

namespace user2{
struct User2{
lib::LibStruct ls{};
void bar{
  ls.foo();
}
}
} //namespace user2

int main(){
//logging init. 

user1::User1 u1{};
user2::User2 u2{};

u1.bar();
u2.bar();
return 0;
}

```

In this case, if I have the logging init in LibStruct - ```quill:get_logger("libStruct")```, I will have all logs in the same sink, which makes me sad, so it is difficult to get for which user something went wrong. 
If I will make logging in User's e.g. constructor ```quill:get_logger("user1")```, I will have to pass the pointer of the logger to the lib and pass it to all structures which are under the LibStruct. as an alternative I can pass the string "user1" to libStruc, so it will pass this name to down hierarchy classes, so, they may pick up logger they need. 
Are there other workarounds? Sorry for off-topic. 

so, to the points: 
1. I used LOG_CURENT_DEBUG not in the whole modules, but just in some places which are of interest for me to debug currently. To find anything important in the run. 
I guess I can achieve this using the filtering procedures you proposed. 
e.g. if I will add some anchor symbol to the log message, and will try to filter it out. 
happens to filter in the logger thread? With dummy filtering the whole story may go slower, isn't it?
2. I'm sorry I've seen that log level names do not contain 'LOG_' just forgot it while I was typing the answer. Sure I can format my logs as I need, but the names of the levels itself are unchangable. But as I said, this is minor, and even creepy.

**Comment by odygrd** [comment]
```c++
#include "quill/Quill.h"

namespace lib
{
// common library used by user_1 and user_2

// common functions need to take quill::Logger* to know who is calling them
void bar(quill::Logger* logger)
{
  // Here we know which module called us and we also have control when changing the log levels
  // of the modules
  LOG_INFO(logger, " Calling bar ");
}

// common classes need to take a quill::Logger* passed by their callers. It can not lookup the 
// quill::Logger* because it does not know who is calling it.
struct LibStruct
{
  // Here we know which module called us and we also have control when changing the log levels
  // of the modules
  explicit LibStruct(quill::Logger* logger) : _logger(logger){};

  void foo() { LOG_INFO(_logger, " Calling foo "); }

private:
  quill::Logger* _logger{nullptr};
};

} // namespace lib

namespace user1
{
// global could be in any include file .e.g user1/typedefs.h
static constexpr char const* logger_name{"user1_logger"};

// rest module code ...
// #include "user1/typedefs.h"
struct User1
{
  // Store the looked up pointer of the module on construction
  quill::Logger* _logger{quill::get_logger(logger_name)};
  
  lib::LibStruct ls{_logger};

  void call_foo() { ls.foo(); }
  void call_bar() { lib::bar(_logger); }
};
} // namespace user1

namespace user2
{
// global could be in any include file .e.g user1/typedefs.h
static constexpr char const* logger_name{"user2_logger"};

// rest module code ...
// #include "user1/typedefs.h"
struct User2
{
  // Store the looked up pointer of the module on construction
  quill::Logger* _logger{quill::get_logger(logger_name)};
  
  lib::LibStruct ls{_logger};

  void call_foo() { ls.foo(); }
  void call_bar() { lib::bar(_logger); }
};
} // namespace user2

int main()
{
  quill::start();

  // create all module loggers
  quill::create_logger(user1::logger_name);
  quill::create_logger(user2::logger_name);

  // logging init.

  user1::User1 u1{};
  user2::User2 u2{};

  u1.call_foo();
  u2.call_foo();
  u1.call_bar();
  u2.call_bar();

  return 0;
}
```

I would do something like the above, that way you know which module is calling `lib` and can disable/enable it. 
The alternative would be to have a logger named `lib_logger` in lib but then you wouldn't be able to disable calls from `user1` and `user2`.
In very low level system libraries I usually don't log anything and just return only the errors by throwing an exception instead.

**Comment by dskachan** [comment]
Hey @odygrd, thanks for your effort. 
yes, looks like the pattern where major classes of my lib will get logger in the constructor is unavoidable. 

Back to the issue - for my purposes, the only last thing why I may want to have a custom severity list - is to make log level interpretation smaller. But I can live with it.
